"""The instrument's error vocabulary: what each code means, in the instrument's own words.

Data only; the decoding over it lives in :mod:`.errors`.

A code is not a flat index. Three layouts share the space:

* On the ``0x02xx``-``0x07xx`` motion faults the low nibble is a motor number, and which motor it
  names depends on the instrument family -- number 3 is the washer head on an EL406 and peri-pump 2
  on a MultiFlo. Those messages carry a ``{motor}`` placeholder for :data:`MOTOR_NAMES` to fill,
  and :data:`FAMILY_MESSAGES` holds the few whose whole sentence differs per family.
* On the ``0x81xx`` link faults the high nibble names the link and the low nibble the failure on
  it, so ``0x8104`` and ``0x8114`` are the same checksum error on two different links. Those come
  from :data:`LINK_NAMES` and :data:`LINK_FAULTS` rather than from :data:`MESSAGES`.
* Everything else is a plain code with one message.

Serial-link statuses share this space with the faults the instrument reports, so they are rows in
:data:`MESSAGES` like any other: ``0x6045`` a failed write, ``0x6048`` an unacknowledged message,
``0x6053`` a reply that never came, ``0x6058`` a port that would not open.
"""

from __future__ import annotations

from pylabrobot.agilent.biotek.lhc.enums.instrument.instrument_family import InstrumentFamily

# The motors each family has, indexed by the motor number a motion fault carries.
MOTOR_NAMES: dict[InstrumentFamily, tuple[str, ...]] = {
  InstrumentFamily.EL406: (
    "Carrier Motor X",
    "Carrier Motor Y",
    "Dispense Head Motor",
    "Washer Head Motor",
    "Syringe A Motor",
    "Syringe B Motor",
    "Peri-pump 1 Motor",
  ),
  InstrumentFamily.MULTIFLO: (
    "Carrier Motor X",
    "Carrier Motor Y",
    "Dispense Head Motor",
    "Peri-pump 2 Motor",
    "Syringe A Motor",
    "Syringe B Motor",
    "Peri-pump 1 Motor",
  ),
  InstrumentFamily.MODEL_405_TS: (
    "Carrier Motor X",
    "Carrier Motor Y",
    "Washer Head Motor",
    "Level Sense Y Motor",
  ),
  InstrumentFamily.MULTIFLO_FX: (
    "Carrier Motor X",
    "Carrier Motor Y",
    "Dispense Head Motor",
    "Peri-pump 2 Motor",
    "Syringe A Motor",
    "Syringe B Motor",
    "Peri-pump 1 Motor",
    "Washer Syringe Motor",
    "Washer Aspirate/Peri-pump RAD Head Motor",
    "Peri-pump RAD Motor Y",
  ),
}

# Filled in for a motor number the instrument family does not have.
UNNAMED_MOTOR = "<motor>"


MESSAGES: dict[int, str] = {
  # no error
  0x0000: "No instrument error.",
  # the task was stopped
  0x0100: "Task was aborted.",
  # motion: sensor transitions and calibration jigs
  0x0200: "Carrier Motor X didn’t find opto sensor transition.",
  0x0201: "Carrier Motor Y didn’t find opto sensor transition.",
  0x0202: "{motor} didn’t find opto sensor transition.",
  0x0203: "{motor} didn’t find opto sensor transition.",
  0x0204: "{motor} didn’t find opto sensor transition.",
  0x0205: "{motor} didn’t find opto sensor transition.",
  0x0206: "{motor} didn’t find opto sensor transition.",
  0x0207: "{motor} didn’t find opto sensor transition.",
  0x0208: "{motor} didn’t find opto sensor transition.",
  0x0209: "{motor} didn’t find opto sensor transition.",
  0x020A: "<motor> didn’t find opto sensor transition.",
  0x020B: "<motor> didn’t find opto sensor transition.",
  0x020C: "<motor> didn’t find opto sensor transition.",
  0x020D: "<motor> didn’t find opto sensor transition.",
  0x020E: "<motor> didn’t find opto sensor transition.",
  0x020F: "<motor> didn’t find opto sensor transition.",
  0x0210: "Carrier Motor X didn’t find opto sensor transition.",
  0x0211: "Carrier Motor Y didn’t find opto sensor transition.",
  0x0212: "{motor} didn’t find opto sensor transition.",
  0x0213: "{motor} didn’t find opto sensor transition.",
  0x0214: "{motor} didn’t find opto sensor transition.",
  0x0215: "{motor} didn’t find opto sensor transition.",
  0x0216: "{motor} didn’t find opto sensor transition.",
  0x0217: "{motor} didn’t find opto sensor transition.",
  0x0218: "{motor} didn’t find opto sensor transition.",
  0x0219: "{motor} didn’t find opto sensor transition.",
  0x021A: "<motor> didn’t find opto sensor transition.",
  0x021B: "<motor> didn’t find opto sensor transition.",
  0x021C: "<motor> didn’t find opto sensor transition.",
  0x021D: "<motor> didn’t find opto sensor transition.",
  0x021E: "<motor> didn’t find opto sensor transition.",
  0x021F: "<motor> didn’t find opto sensor transition.",
  0x0220: "Carrier Motor X didn’t find autocal jig.",
  0x0221: "Carrier Motor Y didn’t find autocal jig.",
  0x0222: "{motor} didn’t find autocal jig.",
  0x0224: "{motor} didn’t find autocal jig.",
  0x0225: "{motor} didn’t find autocal jig.",
  0x0226: "{motor} didn’t find autocal jig.",
  0x0227: "{motor} didn’t find autocal jig.",
  0x0228: "{motor} didn’t find autocal jig.",
  0x0229: "{motor} didn’t find autocal jig.",
  0x022A: "<motor> didn’t find autocal jig.",
  0x022B: "<motor> didn’t find autocal jig.",
  0x022C: "<motor> didn’t find autocal jig.",
  0x022D: "<motor> didn’t find autocal jig.",
  0x022E: "<motor> didn’t find autocal jig.",
  0x022F: "<motor> didn’t find autocal jig.",
  # motion: interlocks and covers
  0x0300: "Carrier Motor X interlock safety switch open.",
  0x0301: "Carrier Motor Y interlock safety switch open.",
  0x0302: "{motor} interlock safety switch open.",
  0x0304: "{motor} interlock safety switch open.",
  0x0305: "{motor} interlock safety switch open.",
  0x0307: "{motor} interlock safety switch open.",
  0x0308: "{motor} interlock safety switch open.",
  0x0309: "{motor} interlock safety switch open.",
  0x030A: "<motor> interlock safety switch open.",
  0x030B: "<motor> interlock safety switch open.",
  0x030C: "<motor> interlock safety switch open.",
  0x030D: "<motor> interlock safety switch open.",
  0x030E: "<motor> interlock safety switch open.",
  0x030F: "<motor> interlock safety switch open.",
  # motion: moves that did not complete
  0x0400: "Carrier Motor X failed positional verify.",
  0x0401: "Carrier Motor Y failed positional verify.",
  0x0402: "{motor} failed positional verify.",
  0x0403: "{motor} failed positional verify.",
  0x0404: "{motor} failed positional verify.",
  0x0405: "{motor} failed positional verify.",
  0x0406: "{motor} failed positional verify.",
  0x0407: "{motor} failed positional verify.",
  0x0408: "{motor} failed positional verify.",
  0x0409: "{motor} failed positional verify.",
  0x040A: "<motor> failed positional verify.",
  0x040B: "<motor> failed positional verify.",
  0x040C: "<motor> failed positional verify.",
  0x040D: "<motor> failed positional verify.",
  0x040E: "<motor> failed positional verify.",
  0x040F: "<motor> failed positional verify.",
  # motion: positions not reached or not held
  0x0500: "Carrier Motor X not homed successfully.",
  0x0501: "Carrier Motor Y not homed successfully.",
  0x0502: "{motor} not homed successfully.",
  0x0503: "{motor} not homed successfully.",
  0x0504: "{motor} not homed successfully.",
  0x0505: "{motor} not homed successfully.",
  0x0506: "{motor} not homed successfully.",
  0x0507: "{motor} not homed successfully.",
  0x0508: "{motor} not homed successfully.",
  0x0509: "{motor} not homed successfully.",
  0x050A: "<motor> not homed successfully.",
  0x050B: "<motor> not homed successfully.",
  0x050C: "<motor> not homed successfully.",
  0x050D: "<motor> not homed successfully.",
  0x050E: "<motor> not homed successfully.",
  0x050F: "<motor> not homed successfully.",
  # motion: profiles and step limits
  0x0600: "Carrier Motor X currently in use.",
  0x0601: "Carrier Motor Y currently in use.",
  0x0602: "{motor} currently in use.",
  0x0603: "{motor} currently in use.",
  0x0604: "{motor} currently in use.",
  0x0605: "{motor} currently in use.",
  0x0606: "{motor} currently in use.",
  0x0607: "{motor} currently in use.",
  0x0608: "{motor} currently in use.",
  0x0609: "{motor} currently in use.",
  0x060A: "<motor> currently in use.",
  0x060B: "<motor> currently in use.",
  0x060C: "<motor> currently in use.",
  0x060D: "<motor> currently in use.",
  0x060E: "<motor> currently in use.",
  0x060F: "<motor> currently in use.",
  # motion: motor drive
  0x0700: "<motor> doesn't exist.",
  0x0701: "<motor> doesn't exist.",
  0x0702: "<motor> doesn't exist.",
  0x0703: "<motor> doesn't exist.",
  0x0704: "<motor> doesn't exist.",
  0x0705: "<motor> doesn't exist.",
  0x0706: "<motor> doesn't exist.",
  0x0707: "<motor> doesn't exist.",
  0x0708: "<motor> doesn't exist.",
  0x0709: "<motor> doesn't exist.",
  0x070A: "<motor> doesn't exist.",
  0x070B: "<motor> doesn't exist.",
  0x070C: "<motor> doesn't exist.",
  0x070D: "<motor> doesn't exist.",
  0x070E: "<motor> doesn't exist.",
  0x070F: "<motor> doesn't exist.",
  # level sensing
  0x0900: "Calibration failed due to limit or process errors.",
  # requests refused by the instrument
  0x0A00: "Invalid plate type selected.",
  # calibration data
  0x0C01: "Requested config/autocal data absent.",
  0x0C02: "Calculated checksum didn't match checksum saved.",
  0x0C03: "Config parameter out of range.",
  # bootcode and processors
  0x1001: "Bootcode checksum error at powerup.",
  0x1002: "Bootcode error unknown.",
  0x1003: "Bootcode page program error.",
  0x1004: "Bootcode block size error.",
  0x1005: "Bootcode invalid processor signature.",
  0x1006: "Bootcode memory exceeded.",
  0x1007: "Bootcode invalid slave port.",
  0x1008: "Bootcode invalid slave response.",
  0x1009: "Bootcode invalid processor detected.",
  0x1010: "Bootcode download checksum error.",
  0x1250: "UI Processor internal RAM failure.",
  0x1251: "MC Processor internal RAM failure.",
  # fluid path: syringes, pumps, valves and bottles
  0x1300: "Invalid syringe",
  0x1301: "Syringe is not connected",
  0x1302: "Unable to initialize syringe",
  0x1303: "Unable to initialize syringe sensor clear",
  0x1304: "Syringe dispense volume out of calibration range",
  0x1305: "Invalid syringe operation",
  0x1306: "Syringe A FMEA check error",
  0x1307: "Syringe B FMEA check error",
  0x1355: "The Peri-pump module is not configured",
  0x1356: "Invalid Peri-pump dispense position",
  0x1357: "The second Peri-pump module is required",
  0x1358: "This instrument does not support 0.5 µL Peri-pump dispense volume",
  0x1400: "No vacuum pressure detected after turning on the vacuum pump",
  0x1401: "The waste bottles must be emptied before continuing",
  0x1402: "The valve to be cycle is invalid",
  0x1403: "The magnet adapter height is out of range",
  0x1404: "Use of the selected plate type is restricted",
  0x1405: "Z Axis height error",
  0x1406: "Invalid Plate type",
  0x1407: "Invalid Step type",
  0x1408: "Invalid plate geometry",
  0x1409: "Invalid carrier type",
  0x1410: "Incompatible hardware configuration",
  0x1411: "Invalid carrier specified",
  0x1412: "Plate clearance error",
  0x1413: "AutoPrime in progress.\r\nPlease wait until AutoPrime completes.",
  0x1414: "AutoPrime is cleaning up.\r\nPlease wait until AutoPrime cleanup completes.",
  0x1415: "An AutoPrime value is out-of-range.",
  0x1416: "Vacuum pressure incorrectly detected prior to starting the vacuum pump.",
  0x1417: "The autocal sensor was not detected in the back of the instrument.",
  0x1430: "Strip washer syringe FMEA check error.",
  0x1431: "Strip washer aspirate head not installed.",
  0x1432: "Strip washer syringe box not connected.",
  0x1433: "Bad step type pointer passed in when finding plate heights.",
  0x1500: (
    "There was no buffer fluid present at the start of a manifold-based protocol or at "
    "the start of an individual step."
  ),
  0x1501: "There was no buffer fluid present immediately before the manifold dispense sequence.",
  0x1502: "The buffer valve selection is invalid",
  0x1503: (
    "The requested volume to be dispensed through the manifold is smaller than the "
    "minimum volume that will be dispensed by the time the DC dispense pump turns on "
    "and the dispense valve is opened."
  ),
  0x1504: (
    "There was no buffer fluid detected flowing through the manifold tubing during a "
    "manifold dispense/prime operation."
  ),
  0x1505: (
    "There was no buffer fluid present at the end of a manifold-based protocol or at "
    "the end of an individual step."
  ),
  0x1506: "The requested carrier Y-axis position is out of range.",
  0x1514: "The Ultrasonic Advantage hardware is not configured.",
  0x1515: "The low-flow cell-wash hardware is not configured",
  0x1516: "Vacuum pressure issue for vacuum filtration",
  0x1517: "The software could not read the vacuum filter hardware consistently.",
  # on-board protocol storage
  0x1600: "Ran out of on-board storage space",
  0x1601: "Ran out of on-board storage space for P-Dispense steps",
  0x1602: "Ran out of on-board storage space for P-Prime steps",
  0x1603: "Ran out of on-board storage space for P-Purge steps",
  0x1604: "Ran out of on-board storage space for S-Dispense steps",
  0x1605: "Ran out of on-board storage space for S-Prime steps",
  0x1606: "Ran out of on-board storage space for W-Wash steps",
  0x1607: "Ran out of on-board storage space for W-Aspirate steps",
  0x1608: "Ran out of on-board storage space for W-Dispense steps",
  0x1609: "Ran out of on-board storage space for W-Prime steps",
  0x160A: "Ran out of on-board storage space for W-AutoClean steps",
  0x160B: "Ran out of on-board storage space for Shake/Soak steps",
  0x160C: "Ran out of on-board storage space for 1536 Wash steps",
  0x160D: "Invalid Step Type encountered",
  0x1610: "Protocol transfer failed.",
  # sensors and their calibration
  0x1700: "Level sensor not installed.",
  0x1701: "Level sensor framing error.",
  0x1702: "Level sensor timing error.",
  0x1703: "Level sensor unknown command.",
  0x1704: "Level sensor parameter error.",
  0x1705: "Level sensor address error.",
  0x1706: "Level sensor error detected but not classified.",
  0x1707: "Level sensor response cmd char != request cmd char.",
  0x1708: "Level sensor command response not long enough.",
  0x1709: "Level sensor command response address not equal to '0'.",
  0x170A: "Level sensor command response checksum error.",
  0x170B: "Level sensor timeout while looking for SOF char.",
  0x170C: "Level sensor RX error - framing error.",
  0x170D: "Level sensor RX error in Mode parameter.",
  0x170E: "Level sensor RX error in Format parameter.",
  0x170F: "Level sensor RX error in Sensitivity parameter.",
  0x1710: "Level sensor RX error in Average parameter.",
  0x1711: "Level sensor RX error in Temp Comp parameter.",
  0x1712: "Level sensor RX error in SDC parameter.",
  0x1713: "Level sensor RX error in SDE parameter.",
  0x1714: "Level sensor RX error in setting configuration.",
  0x1715: "Level sensor error in converting a read to a level.",
  0x1717: "Level sensor echo range error.",
  0x1718: "Level sensor echo width error.",
  0x171A: "Level sensor - motor axis incorrect in FindAxisCenter().",
  0x171C: "In FindAxisCenter() initial read not > threshold.",
  0x171E: "Level sensor - no well edge found - reached step limit.",
  0x171F: "Level sensor - repeated FindAxisCenter() did not converge.",
  0x1720: "Level sensor corner cal memory checksum error.",
  0x1721: "Level sensor A1 cal memory checksum error.",
  0x1722: "Level sensor - carrier height wrong - plate test > 30mm.",
  0x1723: "A plate read was started but not finished successfully.",
  0x1724: "7 reads did not come up with at least 3 good ones.",
  0x1725: "The range of the smallest 3 reads (of 7) was > 0.5mm.",
  0x1726: "Input to McReqLvlSnsZPosn() out of range.",
  0x1727: "The correction factor is out of range.",
  0x1729: "FindLsyParkPosn() could not find the park position.",
  0x172A: "Read Plate or Read One command to MC - invalid Read Type.",
  0x172B: "Row or column was 0 - must start at 1.",
  0x172C: "Well test error - previous config not loaded.",
  0x172D: "Well test error - wrong well.",
  0x1732: "Level sensor - config memory checksum error.",
  0x1733: "Well positions have not been calculated.",
  0x1734: "Level sense correction factor not been calculated.",
  0x1735: "Doing a Carrier Test - no previous Z-Axis cal data in EEPROM.",
  0x1736: "Attempted a Z-axis wash head move with Sensor Y not at park posn.",
  0x1737: "Plate test did not find a plate.",
  0x1738: "Level sensor - config memory checksum error.",
  0x1739: "MC Not all level sensor cal and config data has been loaded.",
  0x173A: "Level sensor transmission buffer should be empty before sending a command.",
  0x173B: "Level sensor - Z-Cal, Z=0, current to cal > +/-0.75mm.",
  0x173C: "Level sensor - Z-Cal, Z=0, factory cal < 23mm or > 29mm.",
  0x173D: "Level sensor - Z-Cal, Z=0, post to pre > +/-0.3mm.",
  0x173E: "Level sensor - Z-Cal, Z=0, < 15.0mm.",
  0x173F: "7 reads did not produce at least 6 good ones.",
  # plate handling
  0x2400: "Parameter limit exceeded.",
  # on-board protocol files
  0x4000: "Program locked so operation denied.",
  0x4010: "Program non erasable so delete denied.",
  0x4020: "Bad checksum when reading program from eeprom.",
  0x4030: "Program not found.",
  0x4040: "Can't save program because no space is available.",
  0x4050: "Program run cancelled by user.",
  # the serial link, and requests this instrument cannot run
  0x6000: "General communication error during download.",
  0x6001: "COM port created by USB converter no longer active.",
  0x6002: "Invalid basecode part number; this is not the correct instrument",
  0x6003: "Invalid Basecode Data Version; basecode needs to be updated.",
  0x6004: "No rows are selected for the specified plate type.",
  0x6005: "Invalid row selection value (must be 0 or 1).",
  0x6006: "This instrument can only process 96-well plates.",
  0x6007: "This instrument can only process 1536-well plates.",
  0x6008: "The 8-tube Syringe Manifold can only be used with 96 and 384-well plates.",
  0x6009: "The 96-tube fixed Washer Manifold can only be used with 96-well plates.",
  0x6010: "The data is invalid or out-of-range.",
  0x6011: "This step type can not be downloaded.",
  0x6012: (
    "Illegal characters in protocol name; valid characters are letters, numbers, spaces, or _-%&"
  ),
  0x6013: "The protocol name length must be 16 characters or less.",
  0x6015: "The specified volume exceeds the cassette maximum limit.",
  0x6016: "Volume is out-of-range.",
  0x6017: "Invalid Flow rate.",
  0x6018: "Invalid number of pre-dispenses.",
  0x6019: "Invalid Horizontal dispense position.",
  0x6020: "Invalid dispense height.",
  0x6021: "Invalid plate clear height.",
  0x6022: "Invalid column selection value (must be 0 or 1).",
  0x6023: "Invalid protocol step type.",
  0x6024: "The Definition String contains invalid data.",
  0x6025: "Manifold conflict between protocol requirements and instrument configuration.",
  0x6026: "Buffer Switching module is required because protocol steps specify different buffers.",
  0x6027: "The Syringe Dispenser is required because the protocol contains Syringe steps.",
  0x6028: (
    "The vacuum filtration carrier must be installed to run this protocol. Make sure "
    "the plate carrier setting is correct."
  ),
  0x6029: "Required cassette does not match other required or installed cassette.",
  0x6030: "Invalid cassette type was specified.",
  0x6031: "The 96-tube Washer Manifold is required for 96 well plates.",
  0x6032: "'Transfer Protocols' is not supported in this version of the software.",
  0x6033: "This step is not supported for 1536 well plates.",
  0x6034: "The 16-tube Syringe Manifold can not be used for this plate type.",
  0x6035: "The 32-tube Syringe Manifold can only be used for 1536 well plates.",
  0x6036: "The 128-tube Washer Manifold is required for 1536 well plates.",
  0x6037: "The 128-tube Washer Manifold can only be used for 1536 well plates.",
  0x6038: "This step only applies to 1536 well plates.",
  0x6039: "Conflicting Column Selection.",
  0x6040: "Invalid baud rate",
  0x6041: "Invalid data bits selection",
  0x6042: "Invalid stop bits selection",
  0x6043: "Invalid parity selection",
  0x6044: "Serial port error",
  0x6045: "Serial write error on selected COM Port",
  0x6046: "Serial read error on selected COM Port",
  0x6047: "Checksum error",
  0x6048: "Serial NAK error",
  0x6049: "Excess data, or not enough data, received",
  0x6050: "Invalid message header",
  0x6051: "Invalid message object",
  0x6052: "Invalid message body size",
  0x6053: (
    "Serial message timeout. \r\n"
    "The most common reasons for this are:\r\n"
    "- a previous hardware error has occurred. Please re-boot.\r\n"
    "- two communication cables are plugged in. Unplug one.\r\n"
    "- the BioStack is not responding. Re-boot the BioStack.\r\n"
    "- the basecode software is in an unknown state."
  ),
  0x6054: "Port handle error",
  0x6055: "Read timeout value is invalid",
  0x6056: "Unauthorized to open the COM port",
  0x6057: "Out of range parameter for the open port function",
  0x6058: "Unable to open the COM port",
  0x6059: "Unable to clear the transmission buffer",
  0x6060: "Unable to close the port",
  0x6061: "Port is no longer available",
  0x6062: "Unhandled exception while transmitting message.",
  0x6063: "The selected plate type is not allowed with this protocol step",
  0x6064: "The protocol specifies a peri-pump that is not available",
  0x6065: "Too few data bytes received from the instrument",
  0x6066: "Ultrasonic cleaning assembly is not installed",
  0x6067: "The Syringe Box is not compatible with the Syringe Manifold",
  0x6070: "Invalid Syringe specified",
  0x6071: "Invalid number of syringe prime cycles",
  0x6072: "Invalid syringe Aspirate Delay value",
  0x6073: "Invalid X-axis offset value",
  0x6074: "Invalid Y-axis offset value",
  0x6075: "Invalid Z-axis offset value",
  0x6076: "Vacuum Filtration not allowed with 1536 well plates",
  0x6080: "Invalid Peri-pump prime duration",
  0x6085: "Invalid minutes:seconds value",
  0x6086: "Invalid hours:minutes value",
  0x6087: "'Move carrier home' is required if the total Shake/Soak durations exceed 1 minute",
  0x6088: "Invalid Shake/Soak options selected",
  0x6089: "Invalid Shake Intensity selected",
  0x6090: "Invalid Washer buffer selected",
  0x6091: "Invalid Washer Aspirate Delay value",
  0x6092: "Invalid Washer Aspirate Travel Rate value",
  0x6093: "Invalid Wash Cycles value",
  0x6094: "Invalid Wash format selected",
  0x6095: "Invalid 'Sectors to Wash'",
  0x6096: "Delay start of Vacuum is required",
  0x6097: (
    "Syringe Dispense Volume must be an integer.\r\n"
    "(decimals allowed only for the 128-pin Syringe manifold)"
  ),
  0x6098: "The Peri-pump cannot run with the pump cover open",
  0x6099: "The Peri-pump assembly is not installed",
  0x6101: "The 405 TS does not support downloading basecode from the host.",
  0x6102: "The Mini-Tube plate must be used with the Mini-Tube Carrier.",
  # manifold verification results
  0x6110: "The Verify Manifold Test input parameters file was not found.",
  0x6111: "The user data file for the Verify Manifold Test could not be read in.",
  0x6112: "The Verify Manifold Test was stopped by user.",
  0x6113: "The Verify Manifold Test is not supported.",
  0x6120: "The carrier is not level.",
  0x6121: "The test had an aspirate scan error.",
  0x6122: "The test had an dispense scan error.",
  0x6123: "Center of well not found where expected for Verify test plate.",
  0x6124: "Incorrect plate installed for Verify test.",
  0x6125: "The well volume following an aspirate indicates insufficient aspiration.",
  0x6126: "The well volume following a dispense indicates insufficient dispense.",
  0x6127: "Scan data could not be returned from the instrument.",
  0x6128: "Invalid well specified.",
  0x6129: "This Verify Manifold Test step was not performed.",
  0x6150: "The mean Dispense Volume is out of range.",
  0x6151: "The Dispense CV % exceeds the maximum threshold.",
  0x6152: "The Aspirate Rate is below the minimum threshold.",
  0x6160: "This step requires Washer components to be installed and connected.",
  0x6161: "The Strip Washer Manifold and the Plate Type are incompatible.",
  0x6162: "The Strip Washer does not support this Plate Type",
  0x6165: "This Peri-pump does not support single well dispensing.",
  0x6166: "The instrument does not support single well dispensing.",
  0x6167: "The Syringe Manifold can only be used with 6-well plates",
  0x6168: "The Syringe Manifold can only be used with 12-well plates",
  0x6169: "The Syringe Manifold can only be used with 24-well plates",
  0x6170: "The Syringe Manifold can only be used with 48-well plates",
  0x6171: "The Cassette for single well dispensing does not support this plate type",
  # firmware, power supplies and internal resources
  0xA000: "Task control block not available.",
  0xA100: "<device> not available.",
  0xA101: "<device> not available.",
  0xA102: "<device> not available.",
  0xA103: "<device> not available.",
  0xA104: "<device> not available.",
  0xA200: "Version strings for multiple uProcessors do not match.",
  0xA300: "<test type> power supply level error.",
  0xA301: "+5v logic power supply level error.",
  0xA302: "+24v system/motor power supply level error.",
  0xA303: "Internal +42v PeriPump power supply level error.",
  0xA304: "Internal reference voltage error.",
  0xA305: "External +42v PeriPump power supply level error.",
  0xA400: "malloc failed.",
  0xA500: "multiple tasks attempted to use display simultaneously.",
  0xA600: "Serial eeprom access error.",
  0xA700: "Motor move steps are being truncated based on the profile.",
}


# The codes whose sentence differs by family rather than by motor name alone.
FAMILY_MESSAGES: dict[tuple[InstrumentFamily, int], str] = {
  (InstrumentFamily.EL406, 0x0223): "Washer Head Motor didn’t find autocal jig.",
  (InstrumentFamily.MULTIFLO, 0x0223): "Peri-pump 2 Motor didn’t find autocal jig.",
  (
    InstrumentFamily.MODEL_405_TS,
    0x0223,
  ): "Level Sense Y Motor didn’t find find park opto sensor transition.",
  (InstrumentFamily.MULTIFLO_FX, 0x0223): "Peri-pump 2 Motor didn’t find autocal jig.",
  (InstrumentFamily.EL406, 0x0303): "Washer Head Motor interlock safety switch open.",
  (
    InstrumentFamily.MULTIFLO,
    0x0303,
  ): "Peri-pump 2 Pump Cover is open. Close the Pump Cover and re-run protocol.",
  (InstrumentFamily.MODEL_405_TS, 0x0303): "Level Sense Y Motor interlock safety switch open.",
  (
    InstrumentFamily.MULTIFLO_FX,
    0x0303,
  ): "Peri-pump 2 Pump Cover is open. Close the Pump Cover and re-run protocol.",
  (
    InstrumentFamily.EL406,
    0x0306,
  ): "Peri-pump 1 Pump Cover is open. Close the Pump Cover and re-run protocol.",
  (
    InstrumentFamily.MULTIFLO,
    0x0306,
  ): "Peri-pump 1 Pump Cover is open. Close the Pump Cover and re-run protocol.",
  (InstrumentFamily.MODEL_405_TS, 0x0306): "<motor> interlock safety switch open.",
  (
    InstrumentFamily.MULTIFLO_FX,
    0x0306,
  ): "Peri-pump 1 Pump Cover is open. Close the Pump Cover and re-run protocol.",
}


# The high nibble of a 0x81xx code. A link with no name here contributes no prefix.
LINK_NAMES: dict[int, str] = {
  0x00: "Error communicating with instrument software.",
  0x10: "UI processor to MC processor internal communications error.",
  0x20: "Instrument to BioStack communications error.",
}

# The low nibble of a 0x81xx code.
LINK_FAULTS: dict[int, str] = {
  0x00: "Message not acknowledged (NAK).",
  0x01: "Timeout while waiting for serial message data.",
  0x02: "Instrument busy and unable to process message.",
  0x03: "Receive buffer overflow error.",
  0x04: "Communication checksum error.",
  0x05: "Invalid structure type in byMsgStructure header field.",
  0x06: "Invalid destination in byMsgDestination header field.",
  0x07: "Message sent to instrument is not supported.",
  0x08: "Message body size exceeds max limit.",
  0x09: "Max number of requests currently running and cannot run the latest request.",
  0x0A: "No request running when response request issued.",
  0x0C: "Response for outstanding request not ready yet.",
  0x0D: "To communicate, the instrument must be at the Main Menu.",
  0x0E: "One or more request parameters are not valid.",
  0x0F: "Command not valid in current state.",
}
