"""ConnectRPC service stubs for DeckService.

Hand-written to match the pattern generated by protoc-gen-connect-python.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.server import (
    ConnectASGIApplication,
    Endpoint,
)

from . import deck_service_pb2 as pb2

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.interceptor import Interceptor
    from connectrpc.request import Headers, RequestContext


_SVC = "pylabrobot.resources.remote.DeckService"


def _method(name: str, input_cls: type, output_cls: type,
            idempotency: IdempotencyLevel = IdempotencyLevel.UNKNOWN) -> MethodInfo:
    return MethodInfo(name=name, service_name=_SVC,
                      input=input_cls, output=output_cls,
                      idempotency_level=idempotency)


# All read-only RPCs use NO_SIDE_EFFECTS for idempotency.
_NS = IdempotencyLevel.NO_SIDE_EFFECTS

# ============================================================
# Method descriptors
# ============================================================

_GET_TREE = _method("GetTree", pb2.GetTreeRequest, pb2.ResourceTree, _NS)
_GET_RESOURCE = _method("GetResource", pb2.ResourceByNameRequest, pb2.ResourceData, _NS)
_HAS_RESOURCE = _method("HasResource", pb2.ResourceByNameRequest, pb2.BoolResponse, _NS)
_GET_TRASH_AREA = _method("GetTrashArea", pb2.Empty, pb2.ResourceData, _NS)
_GET_TRASH_AREA96 = _method("GetTrashArea96", pb2.Empty, pb2.ResourceData, _NS)

_GET_LOCATION_WRT = _method("GetLocationWrt", pb2.GetLocationWrtRequest, pb2.Coordinate, _NS)
_GET_ABSOLUTE_LOCATION = _method("GetAbsoluteLocation", pb2.GetAbsoluteLocationRequest, pb2.Coordinate, _NS)
_GET_ABSOLUTE_ROTATION = _method("GetAbsoluteRotation", pb2.GetAbsoluteRotationRequest, pb2.Rotation, _NS)
_GET_ABSOLUTE_SIZE = _method("GetAbsoluteSize", pb2.GetAbsoluteSizeRequest, pb2.Size, _NS)
_GET_HIGHEST_POINT = _method("GetHighestPoint", pb2.GetHighestPointRequest, pb2.FloatResponse, _NS)
_BATCH_GET_LOCATION_WRT = _method("BatchGetLocationWrt", pb2.BatchGetLocationWrtRequest, pb2.BatchCoordinateResponse, _NS)

_COMPUTE_VOLUME_FROM_HEIGHT = _method("ComputeVolumeFromHeight", pb2.ComputeVolumeHeightRequest, pb2.FloatResponse, _NS)
_COMPUTE_HEIGHT_FROM_VOLUME = _method("ComputeHeightFromVolume", pb2.ComputeVolumeHeightRequest, pb2.FloatResponse, _NS)
_SUPPORTS_COMPUTE_HEIGHT_VOLUME = _method("SupportsComputeHeightVolume", pb2.ResourceByNameRequest, pb2.BoolResponse, _NS)
_HAS_LID = _method("HasLid", pb2.HasLidRequest, pb2.BoolResponse, _NS)

_GET_TIP = _method("GetTip", pb2.GetTipRequest, pb2.TipData, _NS)

_GET_VOLUME_TRACKER_STATE = _method("GetVolumeTrackerState", pb2.ResourceByNameRequest, pb2.VolumeTrackerState, _NS)
_REMOVE_LIQUID = _method("RemoveLiquid", pb2.TrackerOpRequest, pb2.Empty)
_ADD_LIQUID = _method("AddLiquid", pb2.TrackerOpRequest, pb2.Empty)
_BATCH_REMOVE_LIQUID = _method("BatchRemoveLiquid", pb2.BatchTrackerOpRequest, pb2.Empty)
_BATCH_ADD_LIQUID = _method("BatchAddLiquid", pb2.BatchTrackerOpRequest, pb2.Empty)

_GET_TIP_TRACKER_STATE = _method("GetTipTrackerState", pb2.ResourceByNameRequest, pb2.TipTrackerState, _NS)
_REMOVE_TIP = _method("RemoveTip", pb2.TipTrackerOpRequest, pb2.Empty)
_ADD_TIP = _method("AddTip", pb2.TipTrackerOpRequest, pb2.Empty)

_COMMIT_VOLUME_TRACKERS = _method("CommitVolumeTrackers", pb2.CommitRollbackRequest, pb2.Empty)
_ROLLBACK_VOLUME_TRACKERS = _method("RollbackVolumeTrackers", pb2.CommitRollbackRequest, pb2.Empty)
_COMMIT_TIP_TRACKERS = _method("CommitTipTrackers", pb2.CommitRollbackRequest, pb2.Empty)
_ROLLBACK_TIP_TRACKERS = _method("RollbackTipTrackers", pb2.CommitRollbackRequest, pb2.Empty)

_ASSIGN_CHILD = _method("AssignChild", pb2.AssignChildRequest, pb2.Empty)
_UNASSIGN_CHILD = _method("UnassignChild", pb2.UnassignChildRequest, pb2.Empty)


# ============================================================
# Async service protocol
# ============================================================

class DeckService(Protocol):
    async def get_tree(self, request: pb2.GetTreeRequest, ctx: RequestContext) -> pb2.ResourceTree:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_resource(self, request: pb2.ResourceByNameRequest, ctx: RequestContext) -> pb2.ResourceData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def has_resource(self, request: pb2.ResourceByNameRequest, ctx: RequestContext) -> pb2.BoolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_trash_area(self, request: pb2.Empty, ctx: RequestContext) -> pb2.ResourceData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_trash_area96(self, request: pb2.Empty, ctx: RequestContext) -> pb2.ResourceData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_location_wrt(self, request: pb2.GetLocationWrtRequest, ctx: RequestContext) -> pb2.Coordinate:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_absolute_location(self, request: pb2.GetAbsoluteLocationRequest, ctx: RequestContext) -> pb2.Coordinate:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_absolute_rotation(self, request: pb2.GetAbsoluteRotationRequest, ctx: RequestContext) -> pb2.Rotation:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_absolute_size(self, request: pb2.GetAbsoluteSizeRequest, ctx: RequestContext) -> pb2.Size:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_highest_point(self, request: pb2.GetHighestPointRequest, ctx: RequestContext) -> pb2.FloatResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def batch_get_location_wrt(self, request: pb2.BatchGetLocationWrtRequest, ctx: RequestContext) -> pb2.BatchCoordinateResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def compute_volume_from_height(self, request: pb2.ComputeVolumeHeightRequest, ctx: RequestContext) -> pb2.FloatResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def compute_height_from_volume(self, request: pb2.ComputeVolumeHeightRequest, ctx: RequestContext) -> pb2.FloatResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def supports_compute_height_volume(self, request: pb2.ResourceByNameRequest, ctx: RequestContext) -> pb2.BoolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def has_lid(self, request: pb2.HasLidRequest, ctx: RequestContext) -> pb2.BoolResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_tip(self, request: pb2.GetTipRequest, ctx: RequestContext) -> pb2.TipData:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_volume_tracker_state(self, request: pb2.ResourceByNameRequest, ctx: RequestContext) -> pb2.VolumeTrackerState:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def remove_liquid(self, request: pb2.TrackerOpRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_liquid(self, request: pb2.TrackerOpRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def batch_remove_liquid(self, request: pb2.BatchTrackerOpRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def batch_add_liquid(self, request: pb2.BatchTrackerOpRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_tip_tracker_state(self, request: pb2.ResourceByNameRequest, ctx: RequestContext) -> pb2.TipTrackerState:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def remove_tip(self, request: pb2.TipTrackerOpRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def add_tip(self, request: pb2.TipTrackerOpRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def commit_volume_trackers(self, request: pb2.CommitRollbackRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def rollback_volume_trackers(self, request: pb2.CommitRollbackRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def commit_tip_trackers(self, request: pb2.CommitRollbackRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def rollback_tip_trackers(self, request: pb2.CommitRollbackRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def assign_child(self, request: pb2.AssignChildRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def unassign_child(self, request: pb2.UnassignChildRequest, ctx: RequestContext) -> pb2.Empty:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


# ============================================================
# ASGI application
# ============================================================

class DeckServiceASGIApplication(ConnectASGIApplication[DeckService]):
    def __init__(
        self,
        service: DeckService | AsyncGenerator[DeckService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                f"/{_SVC}/GetTree": Endpoint.unary(method=_GET_TREE, function=svc.get_tree),
                f"/{_SVC}/GetResource": Endpoint.unary(method=_GET_RESOURCE, function=svc.get_resource),
                f"/{_SVC}/HasResource": Endpoint.unary(method=_HAS_RESOURCE, function=svc.has_resource),
                f"/{_SVC}/GetTrashArea": Endpoint.unary(method=_GET_TRASH_AREA, function=svc.get_trash_area),
                f"/{_SVC}/GetTrashArea96": Endpoint.unary(method=_GET_TRASH_AREA96, function=svc.get_trash_area96),
                f"/{_SVC}/GetLocationWrt": Endpoint.unary(method=_GET_LOCATION_WRT, function=svc.get_location_wrt),
                f"/{_SVC}/GetAbsoluteLocation": Endpoint.unary(method=_GET_ABSOLUTE_LOCATION, function=svc.get_absolute_location),
                f"/{_SVC}/GetAbsoluteRotation": Endpoint.unary(method=_GET_ABSOLUTE_ROTATION, function=svc.get_absolute_rotation),
                f"/{_SVC}/GetAbsoluteSize": Endpoint.unary(method=_GET_ABSOLUTE_SIZE, function=svc.get_absolute_size),
                f"/{_SVC}/GetHighestPoint": Endpoint.unary(method=_GET_HIGHEST_POINT, function=svc.get_highest_point),
                f"/{_SVC}/BatchGetLocationWrt": Endpoint.unary(method=_BATCH_GET_LOCATION_WRT, function=svc.batch_get_location_wrt),
                f"/{_SVC}/ComputeVolumeFromHeight": Endpoint.unary(method=_COMPUTE_VOLUME_FROM_HEIGHT, function=svc.compute_volume_from_height),
                f"/{_SVC}/ComputeHeightFromVolume": Endpoint.unary(method=_COMPUTE_HEIGHT_FROM_VOLUME, function=svc.compute_height_from_volume),
                f"/{_SVC}/SupportsComputeHeightVolume": Endpoint.unary(method=_SUPPORTS_COMPUTE_HEIGHT_VOLUME, function=svc.supports_compute_height_volume),
                f"/{_SVC}/HasLid": Endpoint.unary(method=_HAS_LID, function=svc.has_lid),
                f"/{_SVC}/GetTip": Endpoint.unary(method=_GET_TIP, function=svc.get_tip),
                f"/{_SVC}/GetVolumeTrackerState": Endpoint.unary(method=_GET_VOLUME_TRACKER_STATE, function=svc.get_volume_tracker_state),
                f"/{_SVC}/RemoveLiquid": Endpoint.unary(method=_REMOVE_LIQUID, function=svc.remove_liquid),
                f"/{_SVC}/AddLiquid": Endpoint.unary(method=_ADD_LIQUID, function=svc.add_liquid),
                f"/{_SVC}/BatchRemoveLiquid": Endpoint.unary(method=_BATCH_REMOVE_LIQUID, function=svc.batch_remove_liquid),
                f"/{_SVC}/BatchAddLiquid": Endpoint.unary(method=_BATCH_ADD_LIQUID, function=svc.batch_add_liquid),
                f"/{_SVC}/GetTipTrackerState": Endpoint.unary(method=_GET_TIP_TRACKER_STATE, function=svc.get_tip_tracker_state),
                f"/{_SVC}/RemoveTip": Endpoint.unary(method=_REMOVE_TIP, function=svc.remove_tip),
                f"/{_SVC}/AddTip": Endpoint.unary(method=_ADD_TIP, function=svc.add_tip),
                f"/{_SVC}/CommitVolumeTrackers": Endpoint.unary(method=_COMMIT_VOLUME_TRACKERS, function=svc.commit_volume_trackers),
                f"/{_SVC}/RollbackVolumeTrackers": Endpoint.unary(method=_ROLLBACK_VOLUME_TRACKERS, function=svc.rollback_volume_trackers),
                f"/{_SVC}/CommitTipTrackers": Endpoint.unary(method=_COMMIT_TIP_TRACKERS, function=svc.commit_tip_trackers),
                f"/{_SVC}/RollbackTipTrackers": Endpoint.unary(method=_ROLLBACK_TIP_TRACKERS, function=svc.rollback_tip_trackers),
                f"/{_SVC}/AssignChild": Endpoint.unary(method=_ASSIGN_CHILD, function=svc.assign_child),
                f"/{_SVC}/UnassignChild": Endpoint.unary(method=_UNASSIGN_CHILD, function=svc.unassign_child),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self) -> str:
        return f"/{_SVC}"


# ============================================================
# Async client
# ============================================================

class DeckServiceClient(ConnectClient):

    async def get_tree(self, request: pb2.GetTreeRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceTree:
        return await self.execute_unary(request=request, method=_GET_TREE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_resource(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceData:
        return await self.execute_unary(request=request, method=_GET_RESOURCE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def has_resource(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BoolResponse:
        return await self.execute_unary(request=request, method=_HAS_RESOURCE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_trash_area(self, request: pb2.Empty, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceData:
        return await self.execute_unary(request=request, method=_GET_TRASH_AREA, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_trash_area96(self, request: pb2.Empty, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceData:
        return await self.execute_unary(request=request, method=_GET_TRASH_AREA96, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_location_wrt(self, request: pb2.GetLocationWrtRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Coordinate:
        return await self.execute_unary(request=request, method=_GET_LOCATION_WRT, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_absolute_location(self, request: pb2.GetAbsoluteLocationRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Coordinate:
        return await self.execute_unary(request=request, method=_GET_ABSOLUTE_LOCATION, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_absolute_rotation(self, request: pb2.GetAbsoluteRotationRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Rotation:
        return await self.execute_unary(request=request, method=_GET_ABSOLUTE_ROTATION, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_absolute_size(self, request: pb2.GetAbsoluteSizeRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Size:
        return await self.execute_unary(request=request, method=_GET_ABSOLUTE_SIZE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_highest_point(self, request: pb2.GetHighestPointRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.FloatResponse:
        return await self.execute_unary(request=request, method=_GET_HIGHEST_POINT, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def batch_get_location_wrt(self, request: pb2.BatchGetLocationWrtRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BatchCoordinateResponse:
        return await self.execute_unary(request=request, method=_BATCH_GET_LOCATION_WRT, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def compute_volume_from_height(self, request: pb2.ComputeVolumeHeightRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.FloatResponse:
        return await self.execute_unary(request=request, method=_COMPUTE_VOLUME_FROM_HEIGHT, headers=headers, timeout_ms=timeout_ms)

    async def compute_height_from_volume(self, request: pb2.ComputeVolumeHeightRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.FloatResponse:
        return await self.execute_unary(request=request, method=_COMPUTE_HEIGHT_FROM_VOLUME, headers=headers, timeout_ms=timeout_ms)

    async def supports_compute_height_volume(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BoolResponse:
        return await self.execute_unary(request=request, method=_SUPPORTS_COMPUTE_HEIGHT_VOLUME, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def has_lid(self, request: pb2.HasLidRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BoolResponse:
        return await self.execute_unary(request=request, method=_HAS_LID, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_tip(self, request: pb2.GetTipRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.TipData:
        return await self.execute_unary(request=request, method=_GET_TIP, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def get_volume_tracker_state(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.VolumeTrackerState:
        return await self.execute_unary(request=request, method=_GET_VOLUME_TRACKER_STATE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def remove_liquid(self, request: pb2.TrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_REMOVE_LIQUID, headers=headers, timeout_ms=timeout_ms)

    async def add_liquid(self, request: pb2.TrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_ADD_LIQUID, headers=headers, timeout_ms=timeout_ms)

    async def batch_remove_liquid(self, request: pb2.BatchTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_BATCH_REMOVE_LIQUID, headers=headers, timeout_ms=timeout_ms)

    async def batch_add_liquid(self, request: pb2.BatchTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_BATCH_ADD_LIQUID, headers=headers, timeout_ms=timeout_ms)

    async def get_tip_tracker_state(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.TipTrackerState:
        return await self.execute_unary(request=request, method=_GET_TIP_TRACKER_STATE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    async def remove_tip(self, request: pb2.TipTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_REMOVE_TIP, headers=headers, timeout_ms=timeout_ms)

    async def add_tip(self, request: pb2.TipTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_ADD_TIP, headers=headers, timeout_ms=timeout_ms)

    async def commit_volume_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_COMMIT_VOLUME_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    async def rollback_volume_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_ROLLBACK_VOLUME_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    async def commit_tip_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_COMMIT_TIP_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    async def rollback_tip_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_ROLLBACK_TIP_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    async def assign_child(self, request: pb2.AssignChildRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_ASSIGN_CHILD, headers=headers, timeout_ms=timeout_ms)

    async def unassign_child(self, request: pb2.UnassignChildRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return await self.execute_unary(request=request, method=_UNASSIGN_CHILD, headers=headers, timeout_ms=timeout_ms)


# ============================================================
# Sync client
# ============================================================

class DeckServiceClientSync(ConnectClientSync):

    def get_tree(self, request: pb2.GetTreeRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceTree:
        return self.execute_unary(request=request, method=_GET_TREE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_resource(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceData:
        return self.execute_unary(request=request, method=_GET_RESOURCE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def has_resource(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BoolResponse:
        return self.execute_unary(request=request, method=_HAS_RESOURCE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_trash_area(self, request: pb2.Empty, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceData:
        return self.execute_unary(request=request, method=_GET_TRASH_AREA, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_trash_area96(self, request: pb2.Empty, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.ResourceData:
        return self.execute_unary(request=request, method=_GET_TRASH_AREA96, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_location_wrt(self, request: pb2.GetLocationWrtRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Coordinate:
        return self.execute_unary(request=request, method=_GET_LOCATION_WRT, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_absolute_location(self, request: pb2.GetAbsoluteLocationRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Coordinate:
        return self.execute_unary(request=request, method=_GET_ABSOLUTE_LOCATION, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_absolute_rotation(self, request: pb2.GetAbsoluteRotationRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Rotation:
        return self.execute_unary(request=request, method=_GET_ABSOLUTE_ROTATION, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_absolute_size(self, request: pb2.GetAbsoluteSizeRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.Size:
        return self.execute_unary(request=request, method=_GET_ABSOLUTE_SIZE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_highest_point(self, request: pb2.GetHighestPointRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.FloatResponse:
        return self.execute_unary(request=request, method=_GET_HIGHEST_POINT, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def batch_get_location_wrt(self, request: pb2.BatchGetLocationWrtRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BatchCoordinateResponse:
        return self.execute_unary(request=request, method=_BATCH_GET_LOCATION_WRT, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def compute_volume_from_height(self, request: pb2.ComputeVolumeHeightRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.FloatResponse:
        return self.execute_unary(request=request, method=_COMPUTE_VOLUME_FROM_HEIGHT, headers=headers, timeout_ms=timeout_ms)

    def compute_height_from_volume(self, request: pb2.ComputeVolumeHeightRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.FloatResponse:
        return self.execute_unary(request=request, method=_COMPUTE_HEIGHT_FROM_VOLUME, headers=headers, timeout_ms=timeout_ms)

    def supports_compute_height_volume(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BoolResponse:
        return self.execute_unary(request=request, method=_SUPPORTS_COMPUTE_HEIGHT_VOLUME, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def has_lid(self, request: pb2.HasLidRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.BoolResponse:
        return self.execute_unary(request=request, method=_HAS_LID, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_tip(self, request: pb2.GetTipRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.TipData:
        return self.execute_unary(request=request, method=_GET_TIP, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def get_volume_tracker_state(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.VolumeTrackerState:
        return self.execute_unary(request=request, method=_GET_VOLUME_TRACKER_STATE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def remove_liquid(self, request: pb2.TrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_REMOVE_LIQUID, headers=headers, timeout_ms=timeout_ms)

    def add_liquid(self, request: pb2.TrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_ADD_LIQUID, headers=headers, timeout_ms=timeout_ms)

    def batch_remove_liquid(self, request: pb2.BatchTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_BATCH_REMOVE_LIQUID, headers=headers, timeout_ms=timeout_ms)

    def batch_add_liquid(self, request: pb2.BatchTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_BATCH_ADD_LIQUID, headers=headers, timeout_ms=timeout_ms)

    def get_tip_tracker_state(self, request: pb2.ResourceByNameRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None, use_get: bool = False) -> pb2.TipTrackerState:
        return self.execute_unary(request=request, method=_GET_TIP_TRACKER_STATE, headers=headers, timeout_ms=timeout_ms, use_get=use_get)

    def remove_tip(self, request: pb2.TipTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_REMOVE_TIP, headers=headers, timeout_ms=timeout_ms)

    def add_tip(self, request: pb2.TipTrackerOpRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_ADD_TIP, headers=headers, timeout_ms=timeout_ms)

    def commit_volume_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_COMMIT_VOLUME_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    def rollback_volume_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_ROLLBACK_VOLUME_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    def commit_tip_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_COMMIT_TIP_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    def rollback_tip_trackers(self, request: pb2.CommitRollbackRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_ROLLBACK_TIP_TRACKERS, headers=headers, timeout_ms=timeout_ms)

    def assign_child(self, request: pb2.AssignChildRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_ASSIGN_CHILD, headers=headers, timeout_ms=timeout_ms)

    def unassign_child(self, request: pb2.UnassignChildRequest, *, headers: Headers | Mapping[str, str] | None = None, timeout_ms: int | None = None) -> pb2.Empty:
        return self.execute_unary(request=request, method=_UNASSIGN_CHILD, headers=headers, timeout_ms=timeout_ms)
