"""Typed, immutable view of a LidValet's on-device settings.

The device exposes its full calibration/configuration via the ``settings``
command as ``NAME = value`` text. Each key is surfaced here as one explicitly
typed attribute (the device ``NAME`` lower-cased); types are inferred from the
device's own values. A :class:`HighResLidValetSettings` is loaded whole from the
device (or a capture) and is frozen once built.
"""

import warnings
from dataclasses import dataclass, fields
from typing import Any, Dict, Iterable, Tuple

try:
  from typing import Literal
except ImportError:  # pragma: no cover
  from typing_extensions import Literal  # type: ignore


# Known LidValet models, as reported by the device's MACHINE_TYPE setting.
# Extend this (and MachineType) when a new model is encountered.
MachineType = Literal["LidValet"]
KNOWN_MACHINE_TYPES: Tuple[str, ...] = ("LidValet",)


@dataclass(frozen=True)
class HighResLidValetSettings:
  """All on-device settings, one typed attribute per device key."""

  product_name: str
  product_description: str
  serial_number: str
  machine_type: str
  rest_server_port: int
  syslog_server: str
  syslog_level: int
  internal_log_level: int
  carousel_home_speed_fast: float
  carousel_home_speed_slow: float
  carousel_home_acceleration: float
  carousel_velocity: float
  carousel_idle_velocity: float
  carousel_acceleration: float
  carousel_abort_deceleration: float
  carousel_jerk: float
  carousel_final_drive_jerk: float
  carousel_stacker_zero_pos: float
  carousel_stacker_0_pos: float
  carousel_stacker_1_pos: float
  carousel_stacker_2_pos: float
  carousel_stacker_count: int
  carousel_count: int
  carousel_autohome_operations: int
  carousel_calibration_offset: float
  upper_carousel_offset: int
  carousel_reverse: str
  carousel_hold: int
  carousel_run: int
  carousel_boost: int
  carousel_idle: int
  spatula_home_speed_fast: float
  spatula_home_speed_slow: float
  spatula_home_acceleration: float
  spatula_velocity: float
  spatula_velocity_with_plate: float
  spatula_acceleration: float
  spatula_abort_deceleration: float
  spatula_jerk: float
  spatula_counts_per_mm: float
  extra_plate_trap_cycle: str
  spatula_rot_motorized: str
  spatula_rot_home_speed_fast: float
  spatula_rot_home_speed_slow: float
  spatula_rot_home_acceleration: float
  spatula_rot_velocity: float
  spatula_rot_acceleration: float
  spatula_rot_abort_deceleration: float
  spatula_rot_jerk: float
  spatula_rot_zero_pos: float
  spatula_rot_stack_pos_0: float
  spatula_rot_stack_pos_1: float
  spatula_rot_stack_pos_2: float
  spatula_rot_nest_1_pos: float
  spatula_rot_nest_2_pos: float
  spatula_rot_nest_3_pos: float
  spatula_rot_nest_4_pos: float
  spatula_rot_nest_5_pos: float
  spatula_rot_nest_6_pos: float
  spatula_rot_nest_7_pos: float
  spatula_rot_nest_8_pos: float
  spatula_rot_nest_9_pos: float
  spatula_rot_nest_10_pos: float
  spatula_rot_nest_21_pos: float
  spatula_rot_nest_22_pos: float
  spatula_rot_nest_23_pos: float
  spatula_rot_nest_24_pos: float
  spatula_rot_nest_51_pos: float
  spatula_rot_nest_52_pos: float
  spatula_rot_nest_61_pos: float
  spatula_rot_nest_62_pos: float
  spatula_rot_nest_63_pos: float
  spatula_rot_nest_64_pos: float
  spatula_rot_nest_65_pos: float
  spatula_rot_nest_66_pos: float
  spatula_rot_nest_67_pos: float
  spatula_rot_nest_68_pos: float
  spatula_rot_nest_69_pos: float
  spatula_slide_motorized: str
  spatula_slide_home_speed_fast: float
  spatula_slide_home_speed_slow: float
  spatula_slide_home_acceleration: float
  spatula_slide_home_offset: float
  spatula_slide_velocity: float
  spatula_slide_acceleration: float
  spatula_slide_abort_deceleration: float
  spatula_slide_jerk: float
  spatula_slide_in_pos_0: float
  spatula_slide_in_pos_1: float
  spatula_slide_in_pos_2: float
  spatula_slide_nest_1_pos: float
  spatula_slide_nest_2_pos: float
  spatula_slide_nest_3_pos: float
  spatula_slide_nest_4_pos: float
  spatula_slide_nest_5_pos: float
  spatula_slide_nest_6_pos: float
  spatula_slide_nest_7_pos: float
  spatula_slide_nest_8_pos: float
  spatula_slide_nest_9_pos: float
  spatula_slide_nest_10_pos: float
  spatula_slide_nest_21_pos: float
  spatula_slide_nest_22_pos: float
  spatula_slide_nest_23_pos: float
  spatula_slide_nest_24_pos: float
  spatula_slide_nest_51_pos: float
  spatula_slide_nest_52_pos: float
  spatula_slide_nest_61_pos: float
  spatula_slide_nest_62_pos: float
  spatula_slide_nest_63_pos: float
  spatula_slide_nest_64_pos: float
  spatula_slide_nest_65_pos: float
  spatula_slide_nest_66_pos: float
  spatula_slide_nest_67_pos: float
  spatula_slide_nest_68_pos: float
  spatula_slide_nest_69_pos: float
  spatula_valve_in: int
  spatula_valve_out: int
  spatula_valve_hold: int
  spatula_valve_brake: int
  spatula_plate_sensor: int
  spatula_plate_release_sensor: int
  spatula_in_limit_switch: int
  spatula_out_limit_switch: int
  inner_user_door_sensor: int
  door_open_sensor_output: int
  nest_count: int
  nest_1_height: float
  nest_2_height: float
  nest_3_height: float
  nest_4_height: float
  nest_5_height: float
  nest_6_height: float
  nest_7_height: float
  nest_8_height: float
  nest_9_height: float
  nest_10_height: float
  nest_21_height: float
  nest_22_height: float
  nest_23_height: float
  nest_24_height: float
  nest_51_height: float
  nest_52_height: float
  nest_61_height: float
  nest_62_height: float
  nest_63_height: float
  nest_64_height: float
  nest_65_height: float
  nest_66_height: float
  nest_67_height: float
  nest_68_height: float
  nest_69_height: float
  nest_1_style: str
  nest_2_style: str
  nest_3_style: str
  nest_4_style: str
  nest_5_style: str
  nest_6_style: str
  nest_7_style: str
  nest_8_style: str
  nest_9_style: str
  nest_10_style: str
  nest_clearance_above: float
  nest_clearance_below: float
  handover_nest_clearance_above: float
  handover_nest_clearance_below: float
  handover_y_rotation_position: float
  conveyor_clearance_above: float
  conveyor_clearance_below: float
  static_nest_clearance_above: float
  static_nest_clearance_below: float
  io_nest_clearance_above: float
  io_nest_clearance_below: float
  nest_1_sense_input: int
  nest_2_sense_input: int
  nest_3_sense_input: int
  nest_4_sense_input: int
  nest_5_sense_input: int
  nest_6_sense_input: int
  nest_7_sense_input: int
  nest_8_sense_input: int
  nest_9_sense_input: int
  nest_10_sense_input: int
  stacker_base_0: float
  stacker_base_1: float
  stacker_base_2: float
  stacker_top_1: float
  barcode_base_0: float
  barcode_base_1: float
  stacker_default_zero_offset: float
  stacker_default_slot_height: float
  stacker_default_slot_count: int
  stacker_clearance_above: float
  stacker_clearance_below: float
  stacker_laser_to_base: float
  stacker_laser_ssd_offset: float
  barcode_scanner: str
  barcode_laser_start: int
  barcode_laser_stop: int
  barcode_gain: int
  barcode_velocity: float
  barcode_acceleration: float
  barcode_config_itf_enable: str
  barcode_config_itf_status: str
  barcode_config_itf_length_1: int
  barcode_config_itf_length_2: int
  barcode_config_itf_range: str
  plate_hold_settle_time: int
  plate_default_height: float
  plate_default_stack_height: float
  plate_default_plate_thickness: float
  plate_type_errors_fatal: str
  manual_big_door: str
  door_0_position: float
  door_height: float
  door_overlap_negative: float
  door_overlap_positive: float
  sterilization_temperature_c: int
  sterilization_soak_time_sec: int
  sterilization_cool_down_time_sec: int
  sterilization_guaranteed_soak_band_c: float
  spin_during_sterilization: str
  environment_baud: int
  environment_type: str
  positive_humidity_control: str
  idle_spin_cutoff_temp_c: int
  door_gasket_valve: int
  big_door_valve: int
  door_1_valve: int
  door_2_valve: int
  door_3_valve: int
  door_4_valve: int
  door_5_valve: int
  door_6_valve: int
  door_7_valve: int
  door_8_valve: int
  door_1_open_sensor: int
  door_2_open_sensor: int
  door_3_open_sensor: int
  door_4_open_sensor: int
  door_5_open_sensor: int
  door_6_open_sensor: int
  door_7_open_sensor: int
  door_8_open_sensor: int
  door_1_close_sensor: int
  door_2_close_sensor: int
  door_3_close_sensor: int
  door_4_close_sensor: int
  door_5_close_sensor: int
  door_6_close_sensor: int
  door_7_close_sensor: int
  door_8_close_sensor: int
  door_ri_open_sensor: int
  door_ri_close_sensor: int
  gasket_deflate_delay_ms: int
  gasket_inflate_delay_ms: int
  big_door_open_delay_ms: int
  big_door_close_delay_ms: int
  door_open_delay_ms: int
  door_close_delay_ms: int
  door_open_signal_address: int
  door_open_signal_active_level: int
  idle_close_big_door_delay_ms: int
  idle_spin_carousel_delay_ms: int
  carousel_idle_spin_active: str
  tubepicker_z_home_speed_fast: int
  tubepicker_z_home_speed_slow: int
  tubepicker_z_home_acceleration: int
  tubepicker_z_velocity: int
  tubepicker_z_acceleration: int
  tubepicker_z_abort_deceleration: int
  tubepicker_z_jerk: int
  tubepicker_xy_home_speed_fast: int
  tubepicker_xy_home_speed_slow: int
  tubepicker_xy_home_acceleration: int
  tubepicker_xy_home_current_limit: int
  tubepicker_xy_home_current_delay: int
  tubepicker_xy_velocity: int
  tubepicker_xy_acceleration: int
  tubepicker_xy_abort_deceleration: int
  tubepicker_xy_jerk: int
  vac_1_enable: int
  vac_2_enable: int
  vac_1_purge: int
  vac_2_purge: int
  lift_1_enable: int
  lift_2_enable: int
  vac_1_sense: int
  vac_2_sense: int
  nest_1_sense: int
  nest_2_sense: int
  vac_3_enable: int
  vac_4_enable: int
  vac_3_purge: int
  vac_4_purge: int
  lift_3_enable: int
  lift_4_enable: int
  vac_3_sense: int
  vac_4_sense: int
  nest_3_sense: int
  nest_4_sense: int
  vac_5_enable: int
  vac_6_enable: int
  vac_5_purge: int
  vac_6_purge: int
  lift_5_enable: int
  lift_6_enable: int
  vac_5_sense: int
  vac_6_sense: int
  nest_5_sense: int
  nest_6_sense: int
  vac_7_enable: int
  vac_8_enable: int
  vac_7_purge: int
  vac_8_purge: int
  lift_7_enable: int
  lift_8_enable: int
  vac_7_sense: int
  vac_8_sense: int
  nest_7_sense: int
  nest_8_sense: int
  active_hotels: int
  nest_rot_home_speed_fast: int
  nest_rot_home_speed_slow: int
  nest_rot_home_acceleration: int
  nest_rot_velocity: int
  nest_rot_acceleration: int
  nest_rot_abort_deceleration: int
  nest_rot_jerk: int
  nest_rot_zero_pos: float
  microspin_door_closed: int
  microspin_door_open: int
  microspin_spindle_home_offset: int
  microspin_bucket_radius_m: float
  microspin_max_velocity_rpm: int
  microspin_spindle_counts_per_rev: int
  microspin_spindle_position_window: int
  microspin_jiggle_size: int
  microspin_jiggle_count: int
  microspin_door_lock_hold_count: int
  microspin_door_velocity: int
  microspin_door_home_velocity: int
  microspin_door_accel: int
  microspin_door_abort_decel: int
  microspin_door_jerk: int
  microspin_spindle_home_velocity: int
  microspin_spindle_velocity: int
  microspin_spindle_accel: float
  microspin_spindle_decel: float
  microspin_spindle_slow_accel: float
  microspin_spindle_slow_decel: float
  microspin_decel_g_threshold: float
  microspin_spindle_abort_decel: float
  microspin_spindle_jerk: int
  microspin_spindle_max_accel: float
  microspin_spindle_max_decel: float
  microspin_idle_spindle_threshold: float
  microspin_bucket_rise_rpm: int
  microspin_plate_lock: int
  microspin_door_unlock: int
  microspin_plate_lock_a: int
  microspin_plate_lock_b: int
  microspin_door_lock_a: int
  microspin_door_lock_b: int
  microspin_balance_sense_a: int
  microspin_balance_sense_b: int
  microspin_balance_sense_c: int
  pico_rot_home_speed_fast: int
  pico_rot_home_speed_slow: int
  pico_rot_home_acceleration: int
  pico_rot_velocity: int
  pico_rot_acceleration: int
  pico_rot_abort_deceleration: int
  pico_rot_jerk: int
  pico_rot_zero_pos: int
  pico_rot_counts_per_rev: int
  pico_stacker_count: int
  sviott_chute_y_coord: float
  sv_sbs_zero_x_mm: float
  sv_sbs_zero_y_mm: float
  sv_sbs_zero_x_prime_mm: float
  sv_sbs_zero_y_prime_mm: float
  sv_sbs_zero_vial_x_mm: float
  sv_sbs_zero_vial_y_mm: float
  sv_sbs_zero_vial_x_prime_mm: float
  sv_sbs_zero_vial_y_prime_mm: float
  sv_nest_to_nest_y_spacing_mm: float
  sv_tray_to_tray_y_spacing_mm: float
  sv_sbs_row_spacing_mm: float
  sv_sbs_col_spacing_mm: float
  sv_sbs_a1_row_offset_mm: float
  sv_sbs_a1_col_offset_mm: float
  sv_sbs_a1_col_offset2_mm: float
  sv_sbs_rows: int
  sv_sbs_cols: int
  sv_barcode_reader_y_coord_mm: float
  sv_high_density_col_spacing_mm: float
  sv_pusher_1_to_gripper_offset_mm: float
  sv_pusher_2_to_gripper_offset_mm: float
  sv_high_density_even_offset_mm: float
  sv_high_density_rows: int
  sv_high_density_cols: int
  sv_nest_lock_position_1_mm: float
  sv_nest_lock_position_2_mm: float
  sv_magnemotion_a1_row_offset_mm: float
  sv_magnemotion_a1_col_offset_mm: float
  sv_magnemotion_even_offset_mm: float
  sv_check_for_pick_error: int
  sv_check_for_place_error: int
  sviott_x_home_fast: int
  sviott_x_home_slow: int
  sviott_x_home_accel: int
  sviott_x_home_current_ma: int
  sviott_x_home_cur_delay_ms: int
  sviott_x_velocity: int
  sviott_x_acceleration: int
  sviott_x_abort_decel: int
  sviott_x_jerk: int
  sviott_x_counts_per_mm: int
  sviott_y_home_fast: int
  sviott_y_home_slow: int
  sviott_y_home_accel: int
  sviott_y_home_current_ma: int
  sviott_y_home_cur_delay_ms: int
  sviott_y_velocity: int
  sviott_y_acceleration: int
  sviott_y_abort_decel: int
  sviott_y_jerk: int
  sviott_y_counts_per_mm: int
  sviott_z_home_fast: int
  sviott_z_home_slow: int
  sviott_z_home_accel: int
  sviott_z_home_current_ma: int
  sviott_z_home_cur_delay_ms: int
  sviott_z_velocity: int
  sviott_z_acceleration: int
  sviott_z_abort_decel: int
  sviott_z_jerk: int
  sviott_z_counts_per_mm: int
  sviott_z_barcode_height_mm: float
  sviott_z_safe_height_mm: float
  sviott_z_floor_height_mm: float
  sviott_tube_height_mm: float
  sviott_gripper_home_fast: int
  sviott_gripper_home_slow: int
  sviott_gripper_home_accel: int
  sviott_gripper_home_current_ma: int
  sviott_gripper_home_cur_delay_ms: int
  sviott_gripper_velocity: int
  sviott_gripper_acceleration: int
  sviott_gripper_abort_decel: int
  sviott_gripper_jerk: int
  sviott_gripper_counts_per_mm: float
  sviott_gripper_open_size_mm: float
  sviott_gripper_close_pos_mm: float
  sviott_gripper_tube_hold_pos: float
  sviott_vial_x_home_fast: int
  sviott_vial_x_home_slow: int
  sviott_vial_x_home_accel: int
  sviott_vial_x_home_current_ma: int
  sviott_vial_x_home_cur_delay_ms: int
  sviott_vial_x_velocity: int
  sviott_vial_x_acceleration: int
  sviott_vial_x_abort_decel: int
  sviott_vial_x_jerk: int
  sviott_vial_x_counts_per_mm: int
  sviott_vial_y_home_fast: int
  sviott_vial_y_home_slow: int
  sviott_vial_y_home_accel: int
  sviott_vial_y_home_current_ma: int
  sviott_vial_y_home_cur_delay_ms: int
  sviott_vial_y_velocity: int
  sviott_vial_y_acceleration: int
  sviott_vial_y_abort_decel: int
  sviott_vial_y_jerk: int
  sviott_vial_y_counts_per_mm: int
  sviott_convey_home_fast: int
  sviott_convey_home_slow: int
  sviott_convey_home_accel: int
  sviott_convey_home_current_ma: int
  sviott_convey_home_cur_delay_ms: int
  sviott_convey_velocity: int
  sviott_convey_acceleration: int
  sviott_convey_abort_decel: int
  sviott_convey_jerk: int
  sviott_convey_counts_per_mm: int
  sviott_convey_unload_pos_mm: float
  sviott_convey_tube_load_pos_mm: float
  sviott_barcode_home_fast: int
  sviott_barcode_home_slow: int
  sviott_barcode_home_accel: int
  sviott_barcode_velocity: int
  sviott_barcode_acceleration: int
  sviott_barcode_abort_decel: int
  sviott_barcode_jerk: int
  sviott_barcode_counts_per_deg: int
  sviott_barcode_retry: str
  sviott_wiggle_mm: int
  sviott_pusher1_control: int
  sviott_pusher2_control: int
  sviott_vial_push_velocity: int
  sviott_vial_push_acceleration: int
  sviott_vial_push_counts_per_mm: float
  sviott_vial_push_present_mm: float
  def_plate_height: float
  def_stack_height: float
  def_plate_thickness: float
  empty_policy: str
  jiggle_count: int
  jiggle_size: int
  has_lock_sensor: str
  lock_sensor_input: int
  carousel_max_position: int
  carousel_max_velocity: int
  carousel_max_acceleration: int
  carousel_max_deceleration: int
  carousel_max_jerk: int
  carousel_home_pos_offset: int
  carousel_home_neg_offset: float
  carousel_home_spin_offset: int
  carousel_homing_speed: int
  carousel_home_fast: int
  carousel_home_slow: int
  carousel_home_accel: int
  carousel_stacker_width_default: float
  carousel_small_flag_width: int
  carousel_large_flag_width: float
  carousel_move_precision: int
  carousel_width_correction_max: int
  carousel_max_moves_undershot: int
  carousel_ring_numbering: str
  carousel_home_stacker: int
  effectuator_extended_position: int
  effectuator_max_position: int
  effectuator_lock_position: int
  effectuator_unlock_position: int
  effectuator_max_velocity: int
  effectuator_max_acceleration: int
  effectuator_abort_deceleration: int
  effectuator_max_jerk: int
  effectuator_home_offset: int
  effectuator_home_fast: int
  effectuator_home_slow: int
  effectuator_home_accel: int
  effectuator_counts_per_micron: float
  spatula_max_position: int
  spatula_max_velocity: int
  spatula_measure_velocity: int
  spatula_max_acceleration: int
  spatula_max_jerk: int
  spatula_home_offset: int
  spatula_home_fast: int
  spatula_home_slow: int
  spatula_home_accel: int
  spatula_nest_offset: float
  spatula_measurement_tolerance: float
  spatula_beam_break_height: float
  spatula_permitted_shortfall: int
  max_transparency_width_um: int
  spatula_counts_per_micron: float
  spatula_lock_position: int
  spatula_base_position: int
  barcode_max_position: int
  barcode_max_velocity: int
  barcode_max_move_velocity: int
  barcode_max_move_acceleration: int
  barcode_abort_deceleration: int
  barcode_max_move_jerk: int
  barcode_max_read_velocity: int
  barcode_home_offset: int
  barcode_home_fast: int
  barcode_home_slow: int
  barcode_home_accel: int
  barcode_counts_per_micron: float
  spatula_slide_safe_position: float
  spatula_slide_barcode_position: float
  nest_safe_rotation_clearance: float
  limit_x_min: float
  limit_x_max: float
  limit_y_min: float
  limit_y_max: float
  limit_z_min: float
  limit_z_max: float
  limit_theta_min: float
  limit_theta_max: float
  limit_g_min: float
  limit_g_max: float
  limit_gy_min: float
  limit_gy_max: float
  limit_p_min: float
  limit_p_max: float
  limit_barcode_min: float
  limit_barcode_max: float
  z_keep_out_1_min: float
  z_keep_out_1_max: float
  z_keep_out_2_min: float
  z_keep_out_2_max: float
  z_keep_out_3_min: float
  z_keep_out_3_max: float
  tundra_door_cycle_active: str
  tundra_door_cycle_time_sec: int
  tundra_door_cycle_open_time_sec: int
  autocal_z_offset: float
  spatula_slide_adjustment: float
  spatula_slide_conveyor_adjustment: float
  theta_hardstop_to_parallel: float
  carousel_calibration_factor: float
  theta_calibration_factor: float
  barcode_height_adjust: float
  tundra_outer_door_cycle_active: str
  tundra_outer_door_cycle_time_sec: int
  tundra_outer_door_cycle_open_time_sec: int
  spatula_door_clearance_below: float
  spatula_door_clearance_above: float
  plate_trap_calibration_mode_output: int
  plate_trap_calibration_input: int
  theta_ccw_positive: str
  plate_trap_motorized: str
  plate_trap_input_status_0: int
  plate_trap_input_status_1: int
  plate_trap_input_status_2: int
  plate_trap_ouput_command_0: int
  plate_trap_ouput_command_1: int
  z_axis_gain_moving_cp: int
  z_axis_gain_moving_ci: int
  z_axis_gain_moving_vp: int
  z_axis_gain_moving_vi: int
  z_axis_gain_moving_pp: int
  z_axis_gain_moving_vff: int
  z_axis_gain_moving_aff: int
  z_axis_gain_stationary_cp: int
  z_axis_gain_stationary_ci: int
  z_axis_gain_stationary_vp: int
  z_axis_gain_stationary_vi: int
  z_axis_gain_stationary_pp: int
  z_axis_gain_stationary_vff: int
  z_axis_gain_stationary_aff: int
  sv_24v_to_tower_input: int
  sv_48v_to_tower_input: int
  weigh_cell_door_output: int
  weigh_cell_door_input_status_0: int
  weigh_cell_door_input_status_1: int
  weigh_cell_door_input_status_2: int
  weigh_cell_led_red_output: int
  weigh_cell_led_green_output: int
  weigh_cell_led_blue_output: int
  axis_x_home_speed_fast: float
  axis_x_home_speed_slow: float
  axis_x_home_acceleration: float
  axis_x_home_offset: float
  axis_x2_home_offset: float
  tray_to_gantry_0_distance: float
  axis_x2_calibration_adjustment: float
  axis_x_calibration_pos: float
  axis_x_velocity: float
  axis_x_acceleration: float
  axis_x_abort_deceleration: float
  axis_x_jerk: float
  axis_y_home_speed_fast: float
  axis_y_home_speed_slow: float
  axis_y_home_acceleration: float
  axis_y_velocity: float
  axis_y_acceleration: float
  axis_y_abort_deceleration: float
  axis_y_jerk: float
  axis_z_home_speed_fast: float
  axis_z_home_speed_slow: float
  axis_z_home_acceleration: float
  axis_z_home_offset: float
  axis_z_home_offset_hardstop: float
  axis_z_home_hardstop_current_ma: int
  axis_z_home_hardstop_current_time_ms: int
  axis_z_velocity: float
  axis_z_acceleration: float
  axis_z_abort_deceleration: float
  axis_z_jerk: float
  axis_barcode_home_speed_fast: float
  axis_barcode_home_speed_slow: float
  axis_barcode_home_acceleration: float
  axis_barcode_home_offset: float
  axis_barcode_velocity: float
  axis_barcode_acceleration: float
  axis_barcode_abort_deceleration: float
  axis_barcode_jerk: float
  axis_gripper_home_speed_fast: float
  axis_gripper_home_speed_slow: float
  axis_gripper_home_acceleration: float
  axis_gripper_home_offset: float
  axis_gripper_home_offset_hardstop: float
  axis_gripper_home_hardstop_current_ma: int
  axis_gripper_home_hardstop_current_time_ms: int
  axis_gripper_close_position: float
  axis_gripper_velocity: float
  axis_gripper_acceleration: float
  axis_gripper_abort_deceleration: float
  axis_gripper_jerk: float
  plate_sense_door_open_pos: float
  plate_sense_z_safe_hegiht: float
  height_detect_base: float
  height_detect_positive_adjustment: float
  height_detect_negative_adjustment: float
  height_detect_enable_address: int
  barcode_input_number: int
  height_detect_input_number: int
  stacker_code_clearance_above: float
  stacker_code_clearance_below: float
  stacker_code_height: float
  barcode_fixture_height: float
  barcode_fixture_groove_height: float
  barcode_ideal_stacker_tier_1: float
  barcode_ideal_stacker_tier_2: float
  muting_bank_input_1: int
  muting_bank_input_2: int
  muting_bank_input_3: int
  muting_input_1: int
  muting_input_2: int
  tool_head_sel_0: int
  tool_head_sel_1: int
  tool_head_addr_0: int
  tool_head_addr_1: int
  tool_head_addr_2: int
  tool_head_addr_3: int
  ion_bar_air_output: int
  ion_bar_power_output: int
  busybox_mode: str
  microserve_bus_voltage_threshold: float
  microserve_recover_after_estop: str
  psp_packet_delay: int
  home_trays_to_hardstop: str
  dc_out_1_default_on: str
  dc_out_2_default_on: str
  dc_out_3_default_on: str
  lid_discard_drop_wait_time_ms: int
  lidvalet_plate_dropped_threshold: int
  lidvalet_hold_time_after_unlid: int

  @classmethod
  def from_lines(cls, lines: Iterable[str]) -> "HighResLidValetSettings":
    """Build from the device's ``settings`` output (``NAME = value`` lines)."""
    data: Dict[str, str] = {}
    for line in lines:
      if "=" in line:
        key, _, value = line.partition("=")
        data[key.strip()] = value.strip()

    values: Dict[str, Any] = {}
    missing = []
    for f in fields(cls):
      key = f.name.upper()
      if key not in data:
        missing.append(key)
        continue
      if f.type is int:
        values[f.name] = int(data[key])
      elif f.type is float:
        values[f.name] = float(data[key])
      else:
        values[f.name] = data[key]
    if missing:
      raise ValueError(
        f"settings is missing {len(missing)} expected key(s): "
        + ", ".join(missing[:8])
        + ("..." if len(missing) > 8 else "")
      )
    machine_type = values["machine_type"]
    if machine_type not in KNOWN_MACHINE_TYPES:
      warnings.warn(
        f"unknown LidValet model {machine_type!r}; please contribute it to "
        "MachineType / KNOWN_MACHINE_TYPES",
        stacklevel=2,
      )
    return cls(**values)
