repos:
  - repo: local
    hooks:
      - id: check fix
        name: check fix
        entry: python -m ruff check --fix pylabrobot
        language: system
        pass_filenames: false
      - id: format
        name: format
        entry: python -m ruff format pylabrobot
        language: system
        pass_filenames: false
      - id: run-typecheck
        name: Run typecheck
        entry: python -m mypy pylabrobot --check-untyped-defs
        language: system
        pass_filenames: false
