# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from pylabrobot.liconic.storex.experimental_server import (
  storex_pb2 as pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2,
)


class StoreXServiceStub(object):
  """The service owns the StoreX resource tree. A workcell receives a copy of a
  plate only through the loading-tray transfer protocol.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
        channel: A grpc.Channel.
    """
    self.GetState = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/GetState",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoreXState.FromString,
    )
    self.Initialize = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/Initialize",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
    )
    self.FetchPlate = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/FetchPlate",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.FetchPlateRequest.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.PlateSnapshot.FromString,
    )
    self.ClaimTrayPlate = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/ClaimTrayPlate",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.ClaimTrayPlateRequest.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.ClaimTrayPlateResponse.FromString,
    )
    self.CompleteTransfer = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/CompleteTransfer",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.TransferRequest.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
    )
    self.ReleaseTransfer = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/ReleaseTransfer",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.TransferRequest.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
    )
    self.RegisterTrayPlate = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/RegisterTrayPlate",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.RegisterTrayPlateRequest.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.PlateSnapshot.FromString,
    )
    self.StoreTrayPlate = channel.unary_unary(
      "/pylabrobot.liconic.storex.v1.StoreXService/StoreTrayPlate",
      request_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoreTrayPlateRequest.SerializeToString,
      response_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoredPlate.FromString,
    )


class StoreXServiceServicer(object):
  """The service owns the StoreX resource tree. A workcell receives a copy of a
  plate only through the loading-tray transfer protocol.
  """

  def GetState(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def Initialize(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def FetchPlate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def ClaimTrayPlate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def CompleteTransfer(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def ReleaseTransfer(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def RegisterTrayPlate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")

  def StoreTrayPlate(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")


def add_StoreXServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
    "GetState": grpc.unary_unary_rpc_method_handler(
      servicer.GetState,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoreXState.SerializeToString,
    ),
    "Initialize": grpc.unary_unary_rpc_method_handler(
      servicer.Initialize,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.SerializeToString,
    ),
    "FetchPlate": grpc.unary_unary_rpc_method_handler(
      servicer.FetchPlate,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.FetchPlateRequest.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.PlateSnapshot.SerializeToString,
    ),
    "ClaimTrayPlate": grpc.unary_unary_rpc_method_handler(
      servicer.ClaimTrayPlate,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.ClaimTrayPlateRequest.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.ClaimTrayPlateResponse.SerializeToString,
    ),
    "CompleteTransfer": grpc.unary_unary_rpc_method_handler(
      servicer.CompleteTransfer,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.TransferRequest.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.SerializeToString,
    ),
    "ReleaseTransfer": grpc.unary_unary_rpc_method_handler(
      servicer.ReleaseTransfer,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.TransferRequest.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.SerializeToString,
    ),
    "RegisterTrayPlate": grpc.unary_unary_rpc_method_handler(
      servicer.RegisterTrayPlate,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.RegisterTrayPlateRequest.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.PlateSnapshot.SerializeToString,
    ),
    "StoreTrayPlate": grpc.unary_unary_rpc_method_handler(
      servicer.StoreTrayPlate,
      request_deserializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoreTrayPlateRequest.FromString,
      response_serializer=pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoredPlate.SerializeToString,
    ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
    "pylabrobot.liconic.storex.v1.StoreXService", rpc_method_handlers
  )
  server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class StoreXService(object):
  """The service owns the StoreX resource tree. A workcell receives a copy of a
  plate only through the loading-tray transfer protocol.
  """

  @staticmethod
  def GetState(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/GetState",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoreXState.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )

  @staticmethod
  def Initialize(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/Initialize",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )

  @staticmethod
  def FetchPlate(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/FetchPlate",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.FetchPlateRequest.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.PlateSnapshot.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )

  @staticmethod
  def ClaimTrayPlate(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/ClaimTrayPlate",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.ClaimTrayPlateRequest.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.ClaimTrayPlateResponse.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )

  @staticmethod
  def CompleteTransfer(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/CompleteTransfer",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.TransferRequest.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )

  @staticmethod
  def ReleaseTransfer(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/ReleaseTransfer",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.TransferRequest.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.Empty.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )

  @staticmethod
  def RegisterTrayPlate(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/RegisterTrayPlate",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.RegisterTrayPlateRequest.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.PlateSnapshot.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )

  @staticmethod
  def StoreTrayPlate(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/pylabrobot.liconic.storex.v1.StoreXService/StoreTrayPlate",
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoreTrayPlateRequest.SerializeToString,
      pylabrobot_dot_liconic_dot_storex_dot_experimental__server_dot_storex__pb2.StoredPlate.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
    )
