# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_demo import resource_tree_pb2 as resource__tree__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in resource_tree_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ResourceTreeServiceStub(object):
    """The service

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTree = channel.unary_unary(
                '/resource_tree.ResourceTreeService/GetTree',
                request_serializer=resource__tree__pb2.GetTreeRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.TreeResponse.FromString,
                _registered_method=True)
        self.GetResource = channel.unary_unary(
                '/resource_tree.ResourceTreeService/GetResource',
                request_serializer=resource__tree__pb2.GetResourceRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.GetChildren = channel.unary_unary(
                '/resource_tree.ResourceTreeService/GetChildren',
                request_serializer=resource__tree__pb2.GetChildrenRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.ChildrenResponse.FromString,
                _registered_method=True)
        self.AssignChild = channel.unary_unary(
                '/resource_tree.ResourceTreeService/AssignChild',
                request_serializer=resource__tree__pb2.AssignChildRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.UnassignChild = channel.unary_unary(
                '/resource_tree.ResourceTreeService/UnassignChild',
                request_serializer=resource__tree__pb2.UnassignChildRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.Empty.FromString,
                _registered_method=True)
        self.Rotate = channel.unary_unary(
                '/resource_tree.ResourceTreeService/Rotate',
                request_serializer=resource__tree__pb2.RotateRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/resource_tree.ResourceTreeService/Move',
                request_serializer=resource__tree__pb2.MoveRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.ResourceResponse.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/resource_tree.ResourceTreeService/Subscribe',
                request_serializer=resource__tree__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=resource__tree__pb2.TreeEvent.FromString,
                _registered_method=True)


class ResourceTreeServiceServicer(object):
    """The service

    """

    def GetTree(self, request, context):
        """Queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildren(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignChild(self, request, context):
        """Mutations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnassignChild(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rotate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Live updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceTreeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTree,
                    request_deserializer=resource__tree__pb2.GetTreeRequest.FromString,
                    response_serializer=resource__tree__pb2.TreeResponse.SerializeToString,
            ),
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=resource__tree__pb2.GetResourceRequest.FromString,
                    response_serializer=resource__tree__pb2.ResourceResponse.SerializeToString,
            ),
            'GetChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildren,
                    request_deserializer=resource__tree__pb2.GetChildrenRequest.FromString,
                    response_serializer=resource__tree__pb2.ChildrenResponse.SerializeToString,
            ),
            'AssignChild': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignChild,
                    request_deserializer=resource__tree__pb2.AssignChildRequest.FromString,
                    response_serializer=resource__tree__pb2.ResourceResponse.SerializeToString,
            ),
            'UnassignChild': grpc.unary_unary_rpc_method_handler(
                    servicer.UnassignChild,
                    request_deserializer=resource__tree__pb2.UnassignChildRequest.FromString,
                    response_serializer=resource__tree__pb2.Empty.SerializeToString,
            ),
            'Rotate': grpc.unary_unary_rpc_method_handler(
                    servicer.Rotate,
                    request_deserializer=resource__tree__pb2.RotateRequest.FromString,
                    response_serializer=resource__tree__pb2.ResourceResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=resource__tree__pb2.MoveRequest.FromString,
                    response_serializer=resource__tree__pb2.ResourceResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=resource__tree__pb2.SubscribeRequest.FromString,
                    response_serializer=resource__tree__pb2.TreeEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'resource_tree.ResourceTreeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('resource_tree.ResourceTreeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ResourceTreeService(object):
    """The service

    """

    @staticmethod
    def GetTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource_tree.ResourceTreeService/GetTree',
            resource__tree__pb2.GetTreeRequest.SerializeToString,
            resource__tree__pb2.TreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource_tree.ResourceTreeService/GetResource',
            resource__tree__pb2.GetResourceRequest.SerializeToString,
            resource__tree__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource_tree.ResourceTreeService/GetChildren',
            resource__tree__pb2.GetChildrenRequest.SerializeToString,
            resource__tree__pb2.ChildrenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignChild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource_tree.ResourceTreeService/AssignChild',
            resource__tree__pb2.AssignChildRequest.SerializeToString,
            resource__tree__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnassignChild(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource_tree.ResourceTreeService/UnassignChild',
            resource__tree__pb2.UnassignChildRequest.SerializeToString,
            resource__tree__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rotate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource_tree.ResourceTreeService/Rotate',
            resource__tree__pb2.RotateRequest.SerializeToString,
            resource__tree__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/resource_tree.ResourceTreeService/Move',
            resource__tree__pb2.MoveRequest.SerializeToString,
            resource__tree__pb2.ResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/resource_tree.ResourceTreeService/Subscribe',
            resource__tree__pb2.SubscribeRequest.SerializeToString,
            resource__tree__pb2.TreeEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
