// {{{ 2 "SubmethodForwardDeclaration" ""
private function ArrayToString( variable & i_array[], variable & o_str ) void ;
private function BuildArrayOfVolumesForChannels( variable strChannels, variable & o_arrayOfVolumes[] ) void ;
private function BuildTempSequenceFromPositions( variable strPositions, sequence & o_seq ) void ;
private function JSON_GetFloatValue( variable i_strKeyName, variable & o_KeyFloatValue ) void ;
private function SendStepReturnToServer( variable stepName, variable stepReturn1, variable stepReturn2, variable stepReturn3, variable stepReturn4 ) void ;
function SendTextMessageToServer( variable str ) void ;
private function StrTokenize( variable strIn, variable strDelimiter, variable & arrTokens[], variable bAttendEmptyTokens ) void ;
private function waitForGUItoContinue(  ) variable ;
function OnAbort(  ) void ;
// }} ""
// {{{ 5 "OnAbort" "Begin"
function OnAbort(  ) void {
// }} ""
// {{ 5 "OnAbort" "InitLocals"
// }} ""
// {{{ 486 1 0 "c8aa765a_4840_468a_9e928b44fa79d891" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHttp::Release(objHttp);
// }} ""
// {{{ 5 "OnAbort" "End"
}
// }} ""
// {{{ 5 "SendTextMessageToServer" "Begin"
function SendTextMessageToServer( variable str ) void {
// }} ""
private object objJSONObject;
private variable strJSON;
// {{ 5 "SendTextMessageToServer" "InitLocals"
// }} ""
// {{{ 456 1 0 "9d5f9d4a_c104_4b47_964b6d97f981a71e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::Create(objJSONObject);
// }} ""
// {{{ 457 1 0 "d0a04705_1adc_4919_b95168834c89f4de" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONObject, Translate("command"), Translate("message"));
// }} ""
// {{{ 458 1 0 "7b9a6cd1_3eee_4085_b3f9548e43fc3424" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONObject, Translate("text"), str);
// }} ""
// {{{ 459 1 0 "6a1c53cf_65ea_4f53_aa2e9111890fecf5" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::GetJson(objJSONObject, strJSON);
// }} ""
// {{{ 460 1 0 "bee8c148_b3ea_490b_8d93d8ed5f24939f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::Release(objJSONObject);
// }} ""
// {{{ 461 1 0 "b965a2fd_f821_4400_b4c777f558ed0772" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHttp::HttpPOST(objHttp, Translate("http://localhost:3221"), strJSON, HSLHttp::ContentType_JSON, Translate(""));
// }} ""
// {{{ 5 "SendTextMessageToServer" "End"
}
// }} ""
// {{{ 5 "waitForGUItoContinue" "Begin"
private function waitForGUItoContinue(  ) variable {
// }} ""
private variable loopCounter1;
private variable serverResponse;
private timer timer1;
// {{ 5 "waitForGUItoContinue" "InitLocals"
// }} ""
// {{ 469 1 0 "73328607_d06a_4d7d_8a5df64da06a1bde" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
serverResponse = Translate("");
// }} ""
// {{{ 470 1 0 "2342f8b3_4765_4edc_9fb9f46cbb1fd20b" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
SendTextMessageToServer(Translate("Waiting for server instructions..."));
// }} ""
// {{{ 471 1 0 "216e1039_788e_4830_8588933e6c542ba1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
TrcTrace(Translate("Waiting for server instructions...."), Translate(""));
// }} ""
// {{ 472 1 0 "29dd5a3e_097e_4463_9c0cf08cd71770a2" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
loopCounter1 = 0;
while (1 == 1)
{
loopCounter1 = loopCounter1 + 1;
// }} ""
// {{ 473 1 0 "c4dace2b_a8f4_4fc9_9e50c0b239d7ce04" "{B31F353E-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == timer1.SetTimer(1) )
{
    MECC::RaiseRuntimeErrorEx(-1355939584, MECC::IDS::stepNameTimerStart, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{ 474 1 0 "89c37599_83e8_4af6_bee17da851eff56a" "{B31F353F-5D80-11d4-A5EB-0050DA737D89}"
if( 0 == timer1.WaitTimer(hslFalse, hslFalse) )
{
    MECC::RaiseRuntimeErrorEx(-1339162368, MECC::IDS::stepNameTimerWait, MECC::IDS::errorStepFailed, "", "HxMetEdCompCmd");
}
// }} ""
// {{{ 475 1 0 "6ec592d0_fe02_41a9_8503db5ccf0e5544" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
serverResponse = HSLHttp::HttpGET(objHttp, Translate("http://localhost:3221"), Translate(""));
// }} ""
// {{ 476 1 0 "c503da39_3ef9_42d6_884bb194cc028ecb" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (serverResponse != "")
{
// }} ""
// {{ 477 1 0 "b1e2e308_ee78_46d0_8a6832649536045e" "{B31F3533-5D80-11d4-A5EB-0050DA737D89}"
break;
// }} ""
// {{ 478 1 0 "c503da39_3ef9_42d6_884bb194cc028ecb" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 479 1 0 "22cefea8_c8d5_41fb_be266dca75060474" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 == 300)
{
// }} ""
// {{ 480 1 0 "19e5c8f7_a1a9_4348_aa41a572942db630" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 481 1 0 "6be46368_bb3e_4ad8_82647d6f52af8c9b" "{B31F3533-5D80-11d4-A5EB-0050DA737D89}"
break;
// }} ""
// {{ 482 1 0 "22cefea8_c8d5_41fb_be266dca75060474" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 483 1 0 "29dd5a3e_097e_4463_9c0cf08cd71770a2" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{{ 484 1 0 "809789b0_bd70_4c1f_b0d808ce120b1d99" "{9EC997CD-FD3B-4280-811B-49E99DCF062C}"
return (serverResponse);
// }} ""
// {{{ 5 "waitForGUItoContinue" "End"
}
// }} ""
// {{{ 5 "SendStepReturnToServer" "Begin"
private function SendStepReturnToServer( variable stepName, variable stepReturn1, variable stepReturn2, variable stepReturn3, variable stepReturn4 ) void {
// }} ""
private variable strJSON;
// {{ 5 "SendStepReturnToServer" "InitLocals"
// }} ""
// {{{ 445 1 0 "2520bd9f_739d_4111_a27d89f8f73ec39e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::Create(objJSONToServer);
// }} ""
// {{{ 446 1 0 "573e16a7_c660_495b_a8079940be604ff7" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONToServer, Translate("command"), Translate("STAR-return"));
// }} ""
// {{{ 447 1 0 "a97c5efa_0ce4_4358_9c51c1893f526b9e" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONToServer, Translate("step-name"), stepName);
// }} ""
// {{{ 448 1 0 "deceb871_e830_4b14_86e626f745ef083a" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONToServer, Translate("step-return1"), stepReturn1);
// }} ""
// {{{ 449 1 0 "00afb5c2_b5db_4458_866a13b6cb332b68" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONToServer, Translate("step-return2"), stepReturn2);
// }} ""
// {{{ 450 1 0 "e52bbd02_b31d_4278_a0f45991eab77d3f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONToServer, Translate("step-return3"), stepReturn3);
// }} ""
// {{{ 451 1 0 "19f99698_3777_4dcf_9fc765c3f221df4b" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::SetStringProperty(objJSONToServer, Translate("step-return4"), stepReturn4);
// }} ""
// {{{ 452 1 0 "7728ac0d_8630_4f61_94af076392758ae1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::GetJson(objJSONToServer, strJSON);
// }} ""
// {{{ 453 1 0 "70d261f2_edc4_49a0_a5a074cd5ab92b74" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::Release(objJSONToServer);
// }} ""
// {{{ 454 1 0 "ee0dd62d_582f_4171_b08e37f6106d9b38" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLHttp::HttpPOST(objHttp, Translate("http://localhost:3221"), strJSON, HSLHttp::ContentType_JSON, Translate(""));
// }} ""
// {{{ 5 "SendStepReturnToServer" "End"
}
// }} ""
// {{{ 5 "BuildTempSequenceFromPositions" "Begin"
private function BuildTempSequenceFromPositions( variable strPositions, sequence & o_seq ) void {
// }} ""
private variable n;
private variable loopCounter1;
private variable strSinglePosition;
private variable arrayOfPositions[];
private variable arraySinglePosition[];
private variable labwareID;
private variable positionID;
// {{ 5 "BuildTempSequenceFromPositions" "InitLocals"
{ sequence __temp; o_seq = __temp; }
// }} ""
// {{ 422 1 0 "d9022e13_e502_4969_a8ee79484e990801" "{4900C1F7-0FB7-4033-8253-760BDB9354DC}"
arrayOfPositions.SetSize(0);
// }} ""
// {{{ 423 1 0 "3e178082_8579_435f_a5db4481bb789d9b" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
StrTokenize(strPositions, Translate(";"), arrayOfPositions, 0);
// }} ""
// {{ 424 1 0 "5d735f26_db1b_4bea_9ee405f4167bb99f" "{72EACF88-8D49-43e3-92C8-2F90E81E3260}"
n=arrayOfPositions.GetSize();
// }} ""
// {{{ 425 1 0 "f497f24b_fd39_417d_8703c0d54662309f" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
SeqRemoveAll(o_seq);
// }} ""
// {{ 426 1 0 "b3c5b47a_24b4_41cc_91d3efba82df56d3" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(loopCounter1 = 0; loopCounter1 < n;)
{
loopCounter1 = loopCounter1 + 1;
// }} ""
// {{ 427 1 0 "fd645546_0433_46a0_8619026e338529fd" "{4900C1F7-0FB7-4033-8253-760BDB9354DC}"
arraySinglePosition.SetSize(0);
// }} ""
// {{ 428 1 0 "91aeb0c4_3176_4356_a19a1027bcdb0af3" "{67A8F1C9-6546-41e9-AD2F-3C54F7818853}"
strSinglePosition=arrayOfPositions.GetAt(loopCounter1-1);
// }} ""
// {{{ 429 1 0 "c2b42369_7829_4c62_b58880fce7867995" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
StrTokenize(strSinglePosition, Translate(","), arraySinglePosition, 0);
// }} ""
// {{ 430 1 0 "016f61c5_fd76_4c74_903df10a03070f7b" "{67A8F1C9-6546-41e9-AD2F-3C54F7818853}"
labwareID=arraySinglePosition.GetAt(1-1);
// }} ""
// {{ 431 1 0 "886fc872_7c3a_4366_959db6d5f265ed7c" "{67A8F1C9-6546-41e9-AD2F-3C54F7818853}"
positionID=arraySinglePosition.GetAt(2-1);
// }} ""
// {{{ 432 1 0 "766a54b4_4c5b_4991_9d8ceea62d26b216" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
SeqAdd(o_seq, labwareID, positionID);
// }} ""
// {{ 433 1 0 "b3c5b47a_24b4_41cc_91d3efba82df56d3" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 434 1 0 "0003c6e9_5b43_438d_bc93be342c3c6b55" "{B31F353A-5D80-11d4-A5EB-0050DA737D89}"
o_seq.SetCurrentPosition(1);
// }} ""
// {{{ 5 "BuildTempSequenceFromPositions" "End"
}
// }} ""
// {{{ 5 "StrTokenize" "Begin"
private function StrTokenize( variable strIn, variable strDelimiter, variable & arrTokens[], variable bAttendEmptyTokens ) void {
// }} ""
private variable strEdit;
private variable posLast;
private variable strToAdd;
private variable posCurrent;
// {{ 5 "StrTokenize" "InitLocals"
// }} ""
// {{ 463 1 0 "500afe4c_98a8_4117_8c279b9994d0b626" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
posCurrent = -1;
// }} ""
// {{ 464 1 0 "6a0bd918_2fda_4e4c_a680454ce2576168" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
posLast = -1;
// }} ""
// {{ 465 1 0 "f65ed315_68ed_4ec0_ba0b3c217e692b25" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
strToAdd = "";
// }} ""
// {{ 466 1 0 "9476acee_e5bb_43d1_bbec232ed01bae08" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
strEdit = strIn;
// }} ""
if( StrGetLength(strEdit) == 0 || StrGetLength(strDelimiter) == 0 )
   return;

posLast = StrGetLength(strEdit);
posCurrent = StrFind(strEdit, strDelimiter);

while (-1 != posCurrent && posLast > 0)
{
   //get tokens before next delimiter char
   strToAdd = StrLeft(strEdit, posCurrent);
   StrTrimRight(strToAdd, "");
   StrTrimLeft (strToAdd, "");

   //add token to our output list
   if( StrGetLength(strToAdd) > 0 )
   {
      arrTokens.AddAsLast(strToAdd);
     // Trace(GetFunctionName(), " adding string to output list: $", strToAdd, "$", "" );
   }
   else
   {
      if( bAttendEmptyTokens )// empty string should also be added
      {
         arrTokens.AddAsLast(strToAdd);
         //Trace(GetFunctionName(), " adding string to output list: $", strToAdd, "$", "" );
      }
   }

   //prepare next loop by removing obsolete characters
   strEdit = StrRight(strEdit, posLast - posCurrent - StrGetLength(strDelimiter) );
   //Trace(GetFunctionName(), " next string = ", strEdit );

   //find next "non-delimiter"
   posCurrent = StrFind(strEdit, strDelimiter);
   posLast = StrGetLength(strEdit);
   //Trace(GetFunctionName(), " next pos = ", posCurrent );

}//end while

//no delimiter left
//add the last part of the string to our output list
if (-1 == posCurrent)// && posLast > 0
{
   if( posLast == 0 && !bAttendEmptyTokens )
      return;

   StrTrimRight(strEdit, "");
   StrTrimLeft (strEdit, "");

   //Trace(GetFunctionName(), " no delimiter left - adding string to output list: $", strEdit, "$", "" );

   arrTokens.AddAsLast(strEdit);
}

// {{{ 5 "StrTokenize" "End"
}
// }} ""
// {{{ 5 "BuildArrayOfVolumesForChannels" "Begin"
private function BuildArrayOfVolumesForChannels( variable strChannels, variable & o_arrayOfVolumes[] ) void {
// }} ""
private variable numOfVolumes;
private variable numOfChannelsInVariable;
private variable n;
private variable loopCounter1;
private variable loopCounter2;
private variable arrSize;
private variable loopCounter3;
private variable intType;
private variable val;
private variable strKeyName;
private variable retVal;
// {{ 5 "BuildArrayOfVolumesForChannels" "InitLocals"
o_arrayOfVolumes.SetSize( 0);
// }} ""
// {{ 387 1 0 "69288f91_eabd_4d15_af5361636ffacbf6" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
strKeyName = Translate("volumes");
// }} ""
// {{ 388 1 0 "bf4c1108_6751_41ee_8d3d3b1a9418548f" "{4900C1F7-0FB7-4033-8253-760BDB9354DC}"
o_arrayOfVolumes.SetSize(0);
// }} ""
// {{{ 389 1 0 "a9cfa743_a769_46a3_b8d7e45a67b3d297" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
arrSize = HSLJsonLib::GetArrayLength(objJSONFromServer, strKeyName);
// }} ""
Trace("ARRAY SIZE=", arrSize);
// {{ 391 1 0 "b87c9973_c0d7_4ea7_a2c09b87b361f56a" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (arrSize > 0)
{
// }} ""
// {{ 392 1 0 "594bebbb_0d54_4893_b20d783de743dd44" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 393 1 0 "00de6afc_bb0d_462a_9dc2b92f146c65b5" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(loopCounter3 = 0; loopCounter3 < arrSize;)
{
loopCounter3 = loopCounter3 + 1;
// }} ""
// {{{ 394 1 0 "77e4b501_92f2_4f0c_a6d4190a62e46da7" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::GetElementType(objJSONFromServer, strKeyName, loopCounter3, intType);
// }} ""
Trace("position=", loopCounter3, "   type=", intType);
// {{ 396 1 0 "445e00ec_c7d7_4544_8e9461646bd8dd61" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (intType == 7)
{
// }} ""
// {{{ 397 1 0 "940108aa_cd62_4d73_ac67398dc647e8e4" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
retVal = HSLJsonLib::GetFloatArrayElement(objJSONFromServer, strKeyName, loopCounter3, v);
// }} ""
Trace("Get float return:", retVal, "  value=",v);
// {{ 399 1 0 "445e00ec_c7d7_4544_8e9461646bd8dd61" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 400 1 0 "789ca750_57e1_442d_85be868bb10a3d24" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (intType == 6)
{
// }} ""
// {{{ 401 1 0 "e714eec1_403f_4efd_b2f2b16627e5d25c" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
HSLJsonLib::GetIntegerArrayElement(objJSONFromServer, strKeyName, loopCounter3, v);
// }} ""
// {{ 402 1 0 "789ca750_57e1_442d_85be868bb10a3d24" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 403 1 0 "6be31b23_f55d_4d15_be6abc9ee4bef664" "{F17B7626-27CB-47f1-8477-8C4158339A6D}"
o_arrayOfVolumes.AddAsLast(v);
// }} ""
// {{ 404 1 0 "00de6afc_bb0d_462a_9dc2b92f146c65b5" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 405 1 0 "b87c9973_c0d7_4ea7_a2c09b87b361f56a" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
else
{
// }} ""
// {{ 406 1 0 "4a4891b3_f877_4b14_85196b7e820554b2" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 407 1 0 "22c7c768_33c4_4975_909e9586375bfe8c" "{7C4EF7A7-39BE-406a-897F-71F3A35B4093}"
JSON_GetFloatValue(strKeyName, v);
// }} ""
// {{ 408 1 0 "4e01e62a_13a2_408e_9fbfb2300d5996ed" "{F17B7626-27CB-47f1-8477-8C4158339A6D}"
o_arrayOfVolumes.AddAsLast(v);
// }} ""
// {{ 409 1 0 "b87c9973_c0d7_4ea7_a2c09b87b361f56a" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 410 1 0 "cc565f65_a92a_43ef_9c052b7f5632aca5" "{72EACF88-8D49-43e3-92C8-2F90E81E3260}"
numOfVolumes=o_arrayOfVolumes.GetSize();
// }} ""
// {{{ 411 1 0 "e49355fb_3fe6_4c8d_930870416e36b708" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
numOfChannelsInVariable = StrGetLength(strChannels);
// }} ""
// {{ 412 1 0 "804bc477_e950_4a14_af5f667c73cf5176" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{ 413 1 0 "b237e1a1_c3e7_4ccb_95cf7fe85cb613a8" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (numOfVolumes < numOfChannelsInVariable)
{
// }} ""
// {{ 414 1 0 "2e73355c_8b11_4423_b345807cae9d5db8" "{B31F3544-5D80-11d4-A5EB-0050DA737D89}"
n = numOfChannelsInVariable - numOfVolumes;
// }} ""
// {{ 415 1 0 "53a650d8_2fc1_4c5b_bd19eda433c2a81a" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
v = o_arrayOfVolumes.ElementAt( numOfVolumes -1);
// }} ""
// {{ 416 1 0 "7b61dafe_a658_4913_a69fbb4439fcf8d7" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(loopCounter1 = 0; loopCounter1 < n;)
{
loopCounter1 = loopCounter1 + 1;
// }} ""
// {{ 417 1 0 "cd047b15_6a02_40f1_adfb116f6bf5d763" "{F17B7626-27CB-47f1-8477-8C4158339A6D}"
o_arrayOfVolumes.AddAsLast(v);
// }} ""
// {{ 418 1 0 "7b61dafe_a658_4913_a69fbb4439fcf8d7" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{ 419 1 0 "b237e1a1_c3e7_4ccb_95cf7fe85cb613a8" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 420 1 0 "b6925417_2401_4996_9e43c2f83275a1d1" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
Util2::Debug::TraceArray(Translate("volumes"), o_arrayOfVolumes);
// }} ""
// {{{ 5 "BuildArrayOfVolumesForChannels" "End"
}
// }} ""
// {{{ 5 "ArrayToString" "Begin"
private function ArrayToString( variable & i_array[], variable & o_str ) void {
// }} ""
private variable arraySize;
private variable loopCounter1;
// {{ 5 "ArrayToString" "InitLocals"
o_str = 0;
// }} ""
// {{ 377 1 0 "1a220255_6ba4_40fb_be39a6a2f4e0065f" "{72EACF88-8D49-43e3-92C8-2F90E81E3260}"
arraySize=i_array.GetSize();
// }} ""
// {{ 378 1 0 "f821c4ff_f1a2_4ad7_9bd77dd8652567cb" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
o_str = Translate("");
// }} ""
// {{ 379 1 0 "18e1e887_ea65_4668_a65d392e862d3c46" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
{
for(loopCounter1 = 0; loopCounter1 < arraySize;)
{
loopCounter1 = loopCounter1 + 1;
// }} ""
// {{ 380 1 0 "afd84a84_8330_46e7_8308e16b5caa05e9" "{67A8F1C9-6546-41e9-AD2F-3C54F7818853}"
v=i_array.GetAt(loopCounter1-1);
// }} ""
// {{{ 381 1 0 "77436fd3_3c87_4f09_9a89259b15ef5bf5" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
o_str = StrConcat2(o_str, v);
// }} ""
// {{ 382 1 0 "2f7dae2d_a8aa_4be3_93de2d7d4468ce4b" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (loopCounter1 < arraySize)
{
// }} ""
// {{{ 383 1 0 "d14fd31e_5de8_46f9_bb359f38de9a08ae" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
o_str = StrConcat2(o_str, Translate(";"));
// }} ""
// {{ 384 1 0 "2f7dae2d_a8aa_4be3_93de2d7d4468ce4b" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 385 1 0 "18e1e887_ea65_4668_a65d392e862d3c46" "{B31F3532-5D80-11d4-A5EB-0050DA737D89}"
}
}
// }} ""
// {{{ 5 "ArrayToString" "End"
}
// }} ""
// {{{ 5 "JSON_GetFloatValue" "Begin"
private function JSON_GetFloatValue( variable i_strKeyName, variable & o_KeyFloatValue ) void {
// }} ""
private variable o_intType;
private variable retVal;
// {{ 5 "JSON_GetFloatValue" "InitLocals"
o_KeyFloatValue = 0;
// }} ""
// {{{ 436 1 0 "8f2f8625_6c9e_4c47_b4698d29df60004a" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
retVal = HSLJsonLib::GetFloatProperty(objJSONFromServer, i_strKeyName, o_KeyFloatValue);
// }} ""
// {{ 437 1 0 "9237a268_49c1_4f25_b740f416c52643dc" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (retVal > 0)
{
// }} ""
// {{ 438 1 0 "5a74df81_6685_4703_8b055144f8d74d45" "{F07B0071-8EFC-11d4-A3BA-002035848439}"

// }} ""
// {{{ 439 1 0 "47bb8c98_9624_40ad_b765abfc6b0d0b49" "{C1F3C015-47B3-4514-9407-AC2E65043419}"
retVal = HSLJsonLib::GetIntegerProperty(objJSONFromServer, i_strKeyName, o_KeyFloatValue);
// }} ""
// {{ 440 1 0 "b8a567ad_3f02_43a5_bb2c0456385ec507" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
if (retVal > 0)
{
// }} ""
// {{ 441 1 0 "5b8a3ec6_8ee4_4887_ab7df29fa494cdc1" "{B31F3543-5D80-11d4-A5EB-0050DA737D89}"
o_KeyFloatValue = 0;
// }} ""
// {{ 442 1 0 "b8a567ad_3f02_43a5_bb2c0456385ec507" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{ 443 1 0 "9237a268_49c1_4f25_b740f416c52643dc" "{B31F3531-5D80-11d4-A5EB-0050DA737D89}"
}
// }} ""
// {{{ 5 "JSON_GetFloatValue" "End"
}
// }} ""
/* {{ 2 "SubmethodInsertLine" "" */ // }} ""
// $$author=Cuevas_A$$valid=0$$time=2017-05-01 15:57$$checksum=33321b70$$length=087$$