"""Which load names Opentrons' own labware catalogue defines.

A ``loadLabware`` command names labware by load name and the robot resolves it
against this catalogue, so a name that is not in it fails on the robot with no
client-side warning. Checking here turns that into an error the caller can read,
and it is also what decides whether a resource gets the vendor's definition or
one synthesized from its own geometry.

Transcribed from Opentrons' own labware definitions
(``shared-data/labware/definitions``) at version 9.1.2. ``catalogue_tests``
re-reads those definitions and fails on any drift, whenever
``opentrons-shared-data`` happens to be installed. A robot only resolves the
names its own software shipped with, so a newer robot may know names this list
does not; add them here when that happens.
"""

from typing import FrozenSet

SHARED_DATA_VERSION = "9.1.2"

_LOAD_NAMES = (
  "agilent_1_reservoir_290ml",
  "appliedbiosystemsmicroamp_384_wellplate_40ul",
  "armadillo_96_wellplate_200ul_pcr_full_skirt",
  "axygen_1_reservoir_90ml",
  "axygen_96_wellplate_500ul",
  "biorad_384_wellplate_50ul",
  "biorad_96_wellplate_200ul_pcr",
  "black_96_well_microtiter_plate_lid",
  "corning_12_wellplate_6.9ml_flat",
  "corning_24_wellplate_3.4ml_flat",
  "corning_384_wellplate_112ul_flat",
  "corning_48_wellplate_1.6ml_flat",
  "corning_6_wellplate_16.8ml_flat",
  "corning_96_wellplate_330ul",
  "corning_96_wellplate_360ul_flat",
  "corning_96_wellplate_360ul_lid",
  "corning_falcon_384_wellplate_130ul_flat",
  "corning_falcon_384_wellplate_130ul_flat_lid",
  "costar_96_wellplate_2.2ml",
  "eppendorf_384_wellplate_45ul",
  "eppendorf_96_tiprack_1000ul_eptips",
  "eppendorf_96_tiprack_10ul_eptips",
  "eppendorf_96_wellplate_1000ul",
  "eppendorf_96_wellplate_150ul",
  "eppendorf_96_wellplate_2000ul",
  "eppendorf_96_wellplate_2000ul_lobind",
  "eppendorf_96_wellplate_350ul_lobind",
  "eppendorf_96_wellplate_500ul",
  "eppendorf_96_wellplate_500ul_lobind",
  "ev_resin_tips_flex_96_labware",
  "ev_resin_tips_flex_96_tiprack_adapter",
  "ev_resin_tips_flex_short_adapter",
  "ev_resin_tips_flex_tall_adapter",
  "geb_96_tiprack_1000ul",
  "geb_96_tiprack_10ul",
  "greiner_384_wellplate_240ul",
  "greiner_96_wellplate_323ul",
  "greiner_96_wellplate_340ul_chimney",
  "greiner_96_wellplate_382ul",
  "ibidi_96_square_well_plate_300ul",
  "ibidi_96_square_well_plate_300ul_lid",
  "milliplex_r_96_well_microtiter_plate",
  "nest_12_reservoir_15ml",
  "nest_12_reservoir_22ml",
  "nest_1_reservoir_195ml",
  "nest_1_reservoir_290ml",
  "nest_24_wellplate_10.4ml",
  "nest_8_reservoir_22ml",
  "nest_96_wellplate_100ul_pcr_full_skirt",
  "nest_96_wellplate_200ul_flat",
  "nest_96_wellplate_2ml_deep",
  "nunc_384_wellplate_100ul",
  "nunc_96_wellplate_450ul",
  "opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical",
  "opentrons_10_tuberack_falcon_4x50ml_6x15ml_conical_acrylic",
  "opentrons_10_tuberack_nest_4x50ml_6x15ml_conical",
  "opentrons_12_well_aluminumblock_tough_22ml",
  "opentrons_15_tuberack_eppendorf_15ml_conical",
  "opentrons_15_tuberack_falcon_15ml_conical",
  "opentrons_15_tuberack_nest_15ml_conical",
  "opentrons_1_trash_1100ml_fixed",
  "opentrons_1_trash_3200ml_fixed",
  "opentrons_1_trash_850ml_fixed",
  "opentrons_1_well_aluminumblock_tough_300ml",
  "opentrons_24_aluminumblock_generic_2ml_screwcap",
  "opentrons_24_aluminumblock_nest_0.5ml_screwcap",
  "opentrons_24_aluminumblock_nest_1.5ml_screwcap",
  "opentrons_24_aluminumblock_nest_1.5ml_snapcap",
  "opentrons_24_aluminumblock_nest_2ml_screwcap",
  "opentrons_24_aluminumblock_nest_2ml_snapcap",
  "opentrons_24_tuberack_eppendorf_1.5ml_safelock_snapcap",
  "opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap",
  "opentrons_24_tuberack_eppendorf_2ml_safelock_snapcap_acrylic",
  "opentrons_24_tuberack_generic_0.75ml_snapcap_acrylic",
  "opentrons_24_tuberack_generic_2ml_screwcap",
  "opentrons_24_tuberack_nest_0.5ml_screwcap",
  "opentrons_24_tuberack_nest_1.5ml_screwcap",
  "opentrons_24_tuberack_nest_1.5ml_snapcap",
  "opentrons_24_tuberack_nest_2ml_screwcap",
  "opentrons_24_tuberack_nest_2ml_snapcap",
  "opentrons_40_aluminumblock_eppendorf_24x2ml_safelock_snapcap_generic_16x0.2ml_pcr_strip",
  "opentrons_4_well_aluminumblock_tough_72ml",
  "opentrons_6_tuberack_falcon_50ml_conical",
  "opentrons_6_tuberack_nest_50ml_conical",
  "opentrons_96_aluminumblock_biorad_wellplate_200ul",
  "opentrons_96_aluminumblock_generic_pcr_strip_200ul",
  "opentrons_96_aluminumblock_nest_wellplate_100ul",
  "opentrons_96_deep_well_adapter",
  "opentrons_96_deep_well_adapter_nest_wellplate_2ml_deep",
  "opentrons_96_deep_well_temp_mod_adapter",
  "opentrons_96_filtertiprack_1000ul",
  "opentrons_96_filtertiprack_10ul",
  "opentrons_96_filtertiprack_200ul",
  "opentrons_96_filtertiprack_20ul",
  "opentrons_96_flat_bottom_adapter",
  "opentrons_96_flat_bottom_adapter_nest_wellplate_200ul_flat",
  "opentrons_96_pcr_adapter",
  "opentrons_96_pcr_adapter_armadillo_wellplate_200ul",
  "opentrons_96_pcr_adapter_nest_wellplate_100ul_pcr_full_skirt",
  "opentrons_96_tiprack_1000ul",
  "opentrons_96_tiprack_10ul",
  "opentrons_96_tiprack_20ul",
  "opentrons_96_tiprack_300ul",
  "opentrons_96_well_aluminum_block",
  "opentrons_96_wellplate_200ul_pcr_full_skirt",
  "opentrons_aluminum_flat_bottom_plate",
  "opentrons_calibration_adapter_heatershaker_module",
  "opentrons_calibration_adapter_temperature_module",
  "opentrons_calibration_adapter_thermocycler_module",
  "opentrons_calibrationblock_short_side_left",
  "opentrons_calibrationblock_short_side_right",
  "opentrons_flex_96_filtertiprack_1000ul",
  "opentrons_flex_96_filtertiprack_200ul",
  "opentrons_flex_96_filtertiprack_20ul",
  "opentrons_flex_96_filtertiprack_50ul",
  "opentrons_flex_96_tiprack_1000ul",
  "opentrons_flex_96_tiprack_200ul",
  "opentrons_flex_96_tiprack_20ul",
  "opentrons_flex_96_tiprack_50ul",
  "opentrons_flex_96_tiprack_adapter",
  "opentrons_flex_deck_riser",
  "opentrons_flex_lid_absorbance_plate_reader_module",
  "opentrons_flex_tiprack_lid",
  "opentrons_tough_12_reservoir_22ml",
  "opentrons_tough_1_reservoir_300ml",
  "opentrons_tough_4_reservoir_72ml",
  "opentrons_tough_pcr_auto_sealing_lid",
  "opentrons_tough_universal_lid",
  "opentrons_universal_flat_adapter",
  "opentrons_universal_flat_adapter_corning_384_wellplate_112ul_flat",
  "opentrons_universal_flat_adapter_type_b",
  "protocol_engine_lid_stack_object",
  "schema3test_96_well_aluminum_block",
  "schema3test_96_wellplate_200ul_pcr_full_skirt",
  "schema3test_96_wellplate_360ul_flat",
  "schema3test_aluminum_flat_bottom_plate",
  "schema3test_flex_96_tiprack_200ul",
  "schema3test_flex_96_tiprack_adapter",
  "schema3test_flex_tiprack_lid",
  "schema3test_tough_pcr_auto_sealing_lid",
  "schema3test_universal_flat_adapter",
  "smc_384_read_plate",
  "thermofisher_nunc_maxisorp_lockwell_elisa",
  "thermoscientific_96_wellplate_800ul",
  "thermoscientific_abgene_96_wellplate_1.2ml",
  "thermoscientificnunc_96_wellplate_1300ul",
  "thermoscientificnunc_96_wellplate_2000ul",
  "tipone_96_tiprack_200ul",
  "usascientific_12_reservoir_22ml",
  "usascientific_96_wellplate_2.4ml_deep",
)

CATALOGUE_LOAD_NAMES: FrozenSet[str] = frozenset(_LOAD_NAMES)


def catalogue_load_names() -> FrozenSet[str]:
  """Every load name the shipped catalogue defines."""
  return CATALOGUE_LOAD_NAMES


def is_catalogue_labware(load_name: str) -> bool:
  """Whether Opentrons ships a definition under this load name."""
  return load_name in CATALOGUE_LOAD_NAMES
