"""STAR backend package."""

from .backend import STAR, STARBackend
from .backend_96head import STARBackend96HeadMixin
from .chatterbox import STARChatterboxBackend
from .errors import (
  AntiDropControlError,
  AreaAlreadyOccupiedError,
  AspirationError,
  BarcodeAlreadyUsedError,
  BarcodeMaskError,
  BarcodeNotUniqueError,
  BarcodeUnreadableError,
  ClotDetectedError,
  CommandNotCompletedError,
  CommandSyntaxError,
  CoverCloseError,
  DecapperError,
  DecapperHandlingError,
  DelimiterError,
  DispenseWithPressureLLDError,
  ElementLostError,
  ElementStillHoldingError,
  HamiltonNoTipError,
  HardwareError,
  IllegalTargetPlatePositionError,
  IllegalUserAccessError,
  ImpossibleToOccupyAreaError,
  ImproperDispensationError,
  IncubationError,
  KitLotExpiredError,
  LiquidLevelError,
  LoadingTrayError,
  NoCarrierBarcodeError,
  NoCarrierError,
  NoElementError,
  NoLabwareError,
  NoTeachInSignalError,
  NotAllowedParameterCombinationError,
  NotAspiratedError,
  NotCompletedError,
  NotDetectedError,
  PositionNotReachableError,
  STARFirmwareError,
  STARModuleError,
  SequencedAspirationWithPressureLLDError,
  SlaveError,
  StopError,
  TADMMeasurementError,
  TipAlreadyFittedError,
  TipTooLittleVolumeError,
  UnexpectedLLDError,
  UnexpectedLabwareError,
  UnknownHamiltonError,
  WashFluidOrWasteError,
  WrongCarrierError,
  WrongLabwareError,
  _module_id_to_module_name,
  convert_star_firmware_error_to_plr_error,
  convert_star_module_error_to_plr_error,
  error_code_to_exception,
  star_firmware_string_to_error,
  trace_information_to_string,
)
from .shared import (
  Head96Information,
  STARBaseMixin,
  _dispensing_mode_for_op,
  _requires_head96,
  need_iswap_parked,
  parse_star_fw_string,
)
