name: Type checking

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    name: Type checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt-get update
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: pip install -e '.[dev]'
      - name: Run Pytest
        run: make typecheck
