name: Typo check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update packages
        run: sudo apt-get update
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Dependencies
        run: pip install pre-commit
      - name: Install pre-commit
        run: pre-commit install
      - name: Check formatting
        run: pre-commit run --all-files
      - name: Run pre-commit (typos)
        run: pre-commit run typos --all-files
